### ISSUE TITLE
Where are the test results in csv from the videos?

### ISSUE THREAD

**Issue by RobinMadelief** [AntonMu/TrainYourOwnYOLO#101]
I am using the example data given with the code (the cat images).

I am observing the output, and especially the 'Detection_Results.csv'-file that is in the Test_Image_Detection_Results folder. I can see that the data is there for the images, but what happened to the data of the videos? How can I create a csv-file with the number of the frame in the video and the label and bounding box information in the table?

**Comment by AntonMu** [comment]
Hi @RobinMadelief because of the high number of frames, video results are not stored in a csv file. But you can add this feature by copying the same code used for images to the section that uses videos: https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/3_Inference/Detector.py

**Comment by RobinMadelief** [comment]
Hi @AntonMu, 

I tried to solve it but I cannot figure out what the right place is to copy the out_df code to. 

In the section for images, I see this:

prediction, image = detect_object(
                (...)
            for single_prediction in prediction:
                    out_df = out_df.append(
                             pd.DataFrame(
                                    ...etc.)

But, for videos it uses the detect_video from keras_yolo3, whereas for images it uses detect_object from utils (as seen in the import section on top of the code). As a result, the video structure is a bit different and there is no 'for prediction in predictions' part, which I thought would be the right place for the code. Do you have any insights on how I can overcome this?

**Comment by RobinMadelief** [comment]
For anyone who is looking to do the same thing, here is what I did to get the dataframe with the annotations from a video. 

Instead of changing the Detector file, you have to go back to the yolo.py file in C:...\TrainYourOwnYOLO\2_Training\src\keras_yolo3

And add the logic from detect_object to the detect_video function:

```
def detect_video(yolo, video_path, output_path=""):
    import cv2

    # Make a dataframe for the prediction outputs
    out_df = pd.DataFrame(
        columns=[
            "frame",
            "xmin",
            "ymin",
            "xmax",
            "ymax",
            "label",
            "confidence",
        ]
    )
    vid = cv2.VideoCapture(video_path)
    if not vid.isOpened():
        raise IOError("Couldn't open webcam or video")
    video_FourCC = cv2.VideoWriter_fourcc(*"mp4v")  # int(vid.get(cv2.CAP_PROP_FOURCC))
    video_fps = vid.get(cv2.CAP_PROP_FPS)
    video_size = (
        int(vid.get(cv2.CAP_PROP_FRAME_WIDTH)),
        int(vid.get(cv2.CAP_PROP_FRAME_HEIGHT)),
    )
    isOutput = True if output_path != "" else False
    if isOutput:
        print(
            "Processing {} with frame size {} at {:.1f} FPS".format(
                os.path.basename(video_path), video_size, video_fps
            )
        )
        # print("!!! TYPE:", type(output_path), type(video_FourCC), type(video_fps), type(video_size))
        out = cv2.VideoWriter(output_path, video_FourCC, video_fps, video_size)
    accum_time = 0
    curr_fps = 0
    fps = "FPS: ??"
    prev_time = timer()
    frame_no = 0
    while vid.isOpened():
        return_value, frame = vid.read()
        if not return_value:
            break
        # opencv images are BGR, translate to RGB
        frame = frame[:, :, ::-1]
        image = Image.fromarray(frame)
        out_pred, image = yolo.detect_image(image, show_stats=False)
        frame_no += 1

        #create csv file for the video
        for single_prediction in out_pred:
            print([[frame_no] + single_prediction])
            out_df = out_df.append(
                pd.DataFrame(
                    [
                    [frame_no]
                    + single_prediction
                    ],
                    columns=[
                        "frame",
                        "xmin",
                        "ymin",
                        "xmax",
                        "ymax",
                        "label",
                        "confidence",
                    ],
                ), sort = False
            )


        result = np.asarray(image)
        curr_time = timer()
        exec_time = curr_time - prev_time
        prev_time = curr_time
        accum_time = accum_time + exec_time
        curr_fps = curr_fps + 1
        if accum_time > 1:
            accum_time = accum_time - 1
            fps = "FPS: " + str(curr_fps)
            curr_fps = 0
        cv2.putText(
            result,
            text=fps,
            org=(3, 15),
            fontFace=cv2.FONT_HERSHEY_SIMPLEX,
            fontScale=0.50,
            color=(255, 0, 0),
            thickness=2,
        )
        # cv2.namedWindow("result", cv2.WINDOW_NORMAL)
        # cv2.imshow("result", result)
        if isOutput:
            out.write(result[:, :, ::-1])
        # if cv2.waitKey(1) & 0xFF == ord('q'):
        #     break

    vid.release()
    out.release()

    return out_df
```

I made it return the out_df, and in Detector.py it can be converted to a csv file. 

```
out_df_video = detect_video(yolo, vid_path, output_path=output_path)
            out_df_video.to_csv(FLAGS.box, index=False) 
```

It should be noted that it doesn't work perfectly, since the timestamp of each frame is not saved (instead, the frame number is saved). Also, the columns are not correct in the new dataframe (the xmax and ymin are being confused). But it is a start :)
