### ISSUE TITLE
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Franky987** [AntonMu/TrainYourOwnYOLO#108]
### System information
- **What is the top-level directory of the model you are using**: 3_Inference
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux via AWS 
- **TensorFlow version (use command below)**: 1.15.2
- **CUDA/cuDNN version**: - 
- **GPU model and memory**: -
- **Exact command to reproduce**: Detector.py

### Describe the problem

When running the detector part of the code, I get the following error message:

```
Traceback (most recent call last):
  File "Detector.py", line 24, in <module>
    from utils import load_extractor_model, load_features, parse_input, detect_object
  File "/home/ec2-user/yolo/TrainYourOwnYOLO/Utils/utils.py", line 2, in <module>
    import cv2
  File "/home/ec2-user/venv_yolo/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```

I have successfully done all the previous steps, including installing the requirements and the training of the weights. How is it possible it doesn't find the libSM.so.6? And what can I do to resolve this?

**Comment by AntonMu** [comment]
Hi @Franky987 have you checked the troubleshooting section to see if anything there could help.
