### ISSUE TITLE
File: Test_Image_Detection_Results is empty after running Detector.py

### ISSUE THREAD

**Issue by msadoun** [AntonMu/TrainYourOwnYOLO#109]
I trained the model on my data but when I run Detector.py nothing fills Test_Image_Detection_Results folder

C:\Users\msadoun\Desktop\TrainYourOwnYOLO\3_Inference>python Detector.py
Using TensorFlow backend.
C:\Users\msadoun\Desktop\TrainYourOwnYOLO\Data\Model_Weights\trained_weights_final.h5 model, anchors, and classes loaded in 7.40sec.
Found 13 input labels: ['Canadian_Goose', 'Teal', 'American_Wigeon', 'Gadwall', 'Mallard', 'Sandhill_Crane', 'Other', 'Snow_Goose', 'Northern_Pintail', 'Redhead', 'Northern_Shoveler', 'Ruddy', 'Ringneck'] ...

and this the folder is empty

what could be the reason?????

**Comment by shahzaibraza37** [comment]
Hi,

Maybe the pictures or videos are not of the format which is written in the detector.py code.
