### ISSUE TITLE
No module named 'progressbar', improvement suggestion

### ISSUE THREAD

**Issue by olafwysocki** [AntonMu/TrainYourOwnYOLO#111]
Hi,
First of all - great job with this tutorial!

Just one suggestion

When I wanted to run 

`python Download_and_Convert_YOLO_weights.py`
There was an error
`ModuleNotFoundError: No module named 'progressbar'`

Probably it was missing in requirements.txt file. Quickly fixed with (for Windows with conda)
`conda install progressbar2`

Best,
Olaf

**Comment by AntonMu** [comment]
Hi @olafwysocki - glad you like it! This is an odd error - progressbar2 is part of the requirements file. So I am not sure what happened there - it may be related to conda. Did you get an error when installing requirements?

**Comment by olafwysocki** [comment]
I restarted the requirements file and following error occurred:


> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - progressbar2==3.46.1
> 
> Current channels:
> 
>   - https://repo.anaconda.com/pkgs/main/win-64
>   - https://repo.anaconda.com/pkgs/main/noarch
>   - https://repo.anaconda.com/pkgs/r/win-64
>   - https://repo.anaconda.com/pkgs/r/noarch
>   - https://repo.anaconda.com/pkgs/msys2/win-64
>   - https://repo.anaconda.com/pkgs/msys2/noarch

**Comment by AntonMu** [comment]
Ok that makes sense. Thanks for checking. Conda is sometimes lagging behind in versions. That's why I personally don't use Conda and also don't use it as part of this repo.
