### ISSUE TITLE
Killed while training

### ISSUE THREAD

**Issue by lofty23** [AntonMu/TrainYourOwnYOLO#113]
```
Epoch 1/51
OMP: Info #251: KMP_AFFINITY: pid 12963 tid 12973 thread 1 bound to OS proc set 0
OMP: Info #251: KMP_AFFINITY: pid 12963 tid 12974 thread 2 bound to OS proc set 0
Killed
```

I am getting this error can someone help please?

**Comment by lofty23** [comment]
Basically the problem was with the batch, i reduced it and worked properly. Thanks for your tutorial. Another question when training is ready can i convert the model to mlmodel?

**Comment by AntonMu** [comment]
Hi @lofty23 - glad it worked! I haven't work with exporting the model to different file formats. But the `h5` file contains all the info.
