### ISSUE TITLE
Issue with model file generation

### ISSUE THREAD

**Issue by abhim701** [AntonMu/TrainYourOwnYOLO#117]
------------------------

### System information
- **What is the top-level directory of the model you are using**:
TrainYourOwnYOLO/
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MAc Book Pro
- **TensorFlow version (use command below)**: 1.15
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

### Describe the problem
Bug:
After my training was successfully complete, trained_weights_final.h5 did not get written to the directory TrainYourOwnYOLO/Data/Model_Weights/ ? I did not notice any errors while training. Could. you please help ?
No error received while training the model.

### Source code / logs
python Detector.py

OSError: Unable to open file (unable to open file: name = 'custom_ObDetect2/TrainYourOwnYOLO/Data/Model_Weights/trained_weights_final.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by AntonMu** [comment]
Have you tried running the `Minimal Example.py`? Do you run into the same problem?

**Comment by abhim701** [comment]
Not sure. I have not tried this. If you can. guide me, I will check Minimal Example.py as well
