### ISSUE TITLE
Use two different weight files for Detection

### ISSUE THREAD

**Issue by shahzaibraza37** [AntonMu/TrainYourOwnYOLO#123]
** System information**
What is the top-level directory of the model you are using:
TrainYourOwnYOLO/
**Have I written custom code (as opposed to using a stock example script provided in the repo):**
No
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04):**
Windows Ananconda Prompt Python
**TensorFlow version (use command below):** 1.13
**CUDA/cuDNN version:** 10.0
**GPU model and memory:** NVIDIA GeForce GTX 1050 Ti and 
**Exact command to reproduce:**  NA

**Describe the problem/Help**

Hi,

I have querry regarding weight files. I have multiple weight files which are trained on different classes and object.
I want to use these multiple weight files simultaneously to detect the objects in the image. Has anyone tried this? Does it work?

**Comment by bertelschmitt** [comment]
It depends on what you want to do. If you evaluate  single images, and if you have all the time in the world, you could initialize YOLO with one model/weights file, look at the picture, note the results, then initialize YOLO with another model/weights file, rinse, repeat. init_yolo() can take several seconds, times two for two models. You definitely would not want to take that route to look at live video ….  The quickest solution would be using two machines, or one machine with two GPUs, one of them passed-through to a VM. Of course, creating a new model containing all the objects would be simplest.

**Comment by shahzaibraza37** [comment]
@bertelschmitt  I use the threading module of python for predicting class simultaneously.

**Comment by bertelschmitt** [comment]
Does it work?

**Comment by shahzaibraza37** [comment]
@bertelschmitt I have made two extra folders in the  "Test_Image_Detection_Results" folder. Then I have made two different detector.py files. One file run on 8 classes and the other on 4 classes. 
Then these detector.py scripts are running via python threading and the results are saved in two different folder in  "Test_Image_Detection_Results"

**Comment by bertelschmitt** [comment]
GPU or CPU?  The instant I initiate one model, nearly all of the 11G of my 1080TI are occupied,

**Comment by shahzaibraza37** [comment]
I am detecting objects in images. I have tested on CPU as well as GPU and the detection process was running smoothly on both.

**Comment by bertelschmitt** [comment]
Interesting. I will have to look into that.

**Comment by shahzaibraza37** [comment]
Goodluck with the project. But I think your problem can be solved by running detection on multi-gpu.

**Comment by NiklasWilson** [comment]
@shahzaibraza37 Do keep in mind that the threading module is under python global interpret lock meaning the threading module can not take advantage of multiple cores. You would need to use a library use as multiprocessing to take advantage of multiple cores. The threading module will only work "well" in scenarios where the CPU is waiting for something like results from a GPU :)

**Comment by bertelschmitt** [comment]
With the [multi-stream-multi-model-multi-GPU version of TrainYourOwnYOLO](https://github.com/bertelschmitt/multistreamYOLO/) we now can run multiple models simultaneously on the same GPU. If that's not enough, we can use multiple GPUs. Multiprocessing, each process completely autonomous
