### ISSUE TITLE
Train to ignore?

### ISSUE THREAD

**Issue by bertelschmitt** [AntonMu/TrainYourOwnYOLO#124]
Is there a possibility to train a model with objects it should NOT RECOGNIZE, i.e. ignore? I use YOLO to monitor a video feed from outside a door, and the model keeps erroneously recognizing the opening door as one of the trained objects. I’d like to feed the model with images of the opening door, along with the instruction to ignore the door. Any ideas?

**Comment by AntonMu** [comment]
Hi @bertelschmitt - currently this feature is not implemented but it is definitely a good addition. There is a discussion on this already -> #43

**Comment by bertelschmitt** [comment]
Great,, thanks, I'll be looking for it

**Comment by bertelschmitt** [comment]
Here is one of those cases. This model is trained on cats. Every afternoon, the model thinks the concrete pad is one of the cats, a very black MrKuro. Most likely because the pad was a background of one of the training images. Of course. the sudden shadow introduces another level of difficulty. I could filter it out in post-processing by looking for a close overlap with a defined rectangle. But if the matter is already on the to-do list, I'll leave it to the experts.

Speaking of close overlap: Sometimes,. the model mis-identifies two classes in very close vicinity within the same frame. Usually,  this is solved via Non Maximum Suppression, where the box with the higher confidence wins, and where the lower-confidence box is thrown out. I could not find this feature in the code. 
![falsekuro](https://user-images.githubusercontent.com/50658314/81376118-d7562100-913d-11ea-8ad7-bf856046af4c.png)

**Comment by AntonMu** [comment]
Hi @bertelschmitt - thank you for the detailed example of your use case. To improve performance you could always increase your training set and then make your threshold value higher. For the non-max impression, every (reasonable) YOLO implementation has non-max impression. You can find it in the [`model.py`](https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/src/keras_yolo3/yolo3/model.py#L256) file. I hope this helps!

**Comment by bertelschmitt** [comment]
Thanks, @AntonMu.  I will look for the NMS, and possibly play with the threshold. As for the training set, I'm already at >7K images for this very limited (but tricky) domain (1 camera, 1 view, 7 cats, 4 of them black ...) but a training set is never done. I'm working with video, and started to re-train just the frames with low confidence, or with wrong classification. A very tedious job :)

**Comment by bertelschmitt** [comment]
Hi, @AntonMu. I looked at the model.py code, and the variable that seems to gear NMS is iou_threshold, right? It's set in the code at 0.5, and I will tighten it up a bit to see what happens. I'm not much concerned with overlapping objects in my use-case,I'm worried more about multiple detection.

**Comment by AntonMu** [comment]
Closing this to have a single discussion.
