### ISSUE TITLE
VOTT and VOTT-not

### ISSUE THREAD

**Issue by bertelschmitt** [AntonMu/TrainYourOwnYOLO#126]
Hi, @AntonMu. To help people get into the rather steep learning curve at higher speed, I wrote a little document covering tips&tricks of VOTT and VOTT-not. VOTT is at the start of each project, a lot of mistakes can be made, and avoided.  How to you want me to go about adding the document?
It could be the start of a series of YOLO-howtos, and having successfully fed myself and my family with writing, I am glad to give back to this great project.

**Comment by AntonMu** [comment]
Hi @bertelschmitt,

Thank you for creating this. You could make a pull request for it and then I can refer to it in an additional section in the readme.

Would that work for you?

Anton

**Comment by bertelschmitt** [comment]
Sure. Let me noodle it a bit, and I'll PR it when done

**Comment by bertelschmitt** [comment]
Done. I hope I didn't mess up too big.

**Comment by AntonMu** [comment]
Sounds good. I don't see the PR, yet. But no rush - whenever you are ready.

**Comment by bertelschmitt** [comment]
[It's here:](https://github.com/bertelschmitt/TrainYourOwnYOLO/pulls)

This is my first pull request, and there is a 95% likelihood I did something wrong

**Comment by AntonMu** [comment]
Hi @bertelschmitt,

Ok no worries - GitHub is always a bit tricky at the start. For the PR, you need to make sure you make it on the upstream branch. I recommend using the [dev branch](https://github.com/AntonMu/TrainYourOwnYOLO/tree/dev).

Also, what I envision is to have a folder or a separate document that has further readings and then link to that folder or document from the main readme. What do you think?

**Comment by bertelschmitt** [comment]
Good idea. It’s all yours. Kindof competes with the readme.

 

B

**Comment by AntonMu** [comment]
Okay - if you make a PR to the dev branch I will start reviewing it and then we can get it merged!

**Comment by bertelschmitt** [comment]
@AntonMu : Please give me a day. I want to follow your suggestion to start a separate file (or folder) for tips&tricks that can be added to, to evolve over time
