### ISSUE TITLE
[Request] Live Streaming Detection

### ISSUE THREAD

**Issue by voltaxvoltax** [AntonMu/TrainYourOwnYOLO#135]
Hello Anton, thank you for providing us this great tool!

I've seen that it allows images and videos as sources, but what about live streams, can you implement that option too?

Thank you!

**Comment by BonJovi1** [comment]
Hi voltaxvoltax,

I implemented the same thing - to detect objects in real-time through my computer's webcam. Here are the modifications I made to Anton's code: 

In `Detector.py, add the following snippet of code towards the end, after checking for images and videos. I got most of it from [here](https://github.com/pythonlessons/YOLOv3-object-detection-tutorial/blob/master/YOLOv3-custom-training/webcam_detect.py).
```
start_time = time.time()
display_time = 2
fps = 0

# we create the video capture object cap
cap = cv2.VideoCapture(0)
if not cap.isOpened():
    raise IOError("Cannot open webcam")

while True:
    ret, frame = cap.read()
    # resize our captured frame if we need
    frame = cv2.resize(frame, None, fx=1.0, fy=1.0, interpolation=cv2.INTER_AREA)
    # save the image
    cv2.imwrite('../Data/Source_Images/Test_Images/frame.jpg', frame)
    img_path='../Data/Source_Images/Test_Images/frame.jpg' 
    # detect object on our frame
    # prediction is saved as frame_catface.jpg in Results folder
    prediction, image = detect_object(
            yolo,
            img_path,
            save_img=save_img,
            save_img_path=FLAGS.output,
            postfix=FLAGS.postfix,
            )

    # now just read the predicted image and do a cv2.imshow()
    image2 = cv2.imread('../Data/Source_Images/Test_Image_Detection_Results/frame_catface.jpg')
    cv2.imshow("Web cam input", image2)
    if cv2.waitKey(25) & 0xFF == ord("q"):
        cv2.destroyAllWindows()
        break

    # calculate FPS
    fps += 1
    TIME = time.time() - start_time
    if TIME > display_time:
        print("FPS:", fps / TIME)
        fps = 0 
        start_time = time.time()

cap.release()
cv2.destroyAllWindows()
yolo.close_session()
# Close the current yolo session
yolo.close_session()
```
This should do the trick. I'm using the same name 'frame.jpg', so the images keep getting overwritten, you can save them frame01, frame02 and so on if you wish.  
Hope this helps!

Best,
Abhinav

**Comment by voltaxvoltax** [comment]
Hi Abhinav!

Thank you, was exactly what I was looking for! :)

**Comment by bertelschmitt** [comment]
I am running similar code as @BonJovi1, and it is working quite well. I do it on live video coming from IP cameras in real-time. To do that, simply run

`cap = cv2.VideoCapture('rtsp://192.168.123.123:554) # or whatever the URL of the cam may be`

**Comment by robisen1** [comment]
> Hi voltaxvoltax,
> 
> I implemented the same thing - to detect objects in real-time through my computer's webcam. Here are the modifications I made to Anton's code:
> 
> In `Detector.py, add the following snippet of code towards the end, after checking for images and videos. I got most of it from [here](https://github.com/pythonlessons/YOLOv3-object-detection-tutorial/blob/master/YOLOv3-custom-training/webcam_detect.py).
> 
> ```
> start_time = time.time()
> display_time = 2
> fps = 0
> 
> # we create the video capture object cap
> cap = cv2.VideoCapture(0)
> if not cap.isOpened():
>     raise IOError("Cannot open webcam")
> 
> while True:
>     ret, frame = cap.read()
>     # resize our captured frame if we need
>     frame = cv2.resize(frame, None, fx=1.0, fy=1.0, interpolation=cv2.INTER_AREA)
>     # save the image
>     cv2.imwrite('../Data/Source_Images/Test_Images/frame.jpg', frame)
>     img_path='../Data/Source_Images/Test_Images/frame.jpg' 
>     # detect object on our frame
>     # prediction is saved as frame_catface.jpg in Results folder
>     prediction, image = detect_object(
>             yolo,
>             img_path,
>             save_img=save_img,
>             save_img_path=FLAGS.output,
>             postfix=FLAGS.postfix,
>             )
> 
>     # now just read the predicted image and do a cv2.imshow()
>     image2 = cv2.imread('../Data/Source_Images/Test_Image_Detection_Results/frame_catface.jpg')
>     cv2.imshow("Web cam input", image2)
>     if cv2.waitKey(25) & 0xFF == ord("q"):
>         cv2.destroyAllWindows()
>         break
> 
>     # calculate FPS
>     fps += 1
>     TIME = time.time() - start_time
>     if TIME > display_time:
>         print("FPS:", fps / TIME)
>         fps = 0 
>         start_time = time.time()
> 
> cap.release()
> cv2.destroyAllWindows()
> yolo.close_session()
> # Close the current yolo session
> yolo.close_session()
> ```
> 
> This should do the trick. I'm using the same name 'frame.jpg', so the images keep getting overwritten, you can save them frame01, frame02 and so on if you wish.
> Hope this helps!
> 
> Best,
> Abhinav

Couple of things. Look at imutils and its threading method. This will allow you to have the read and write in different threads. On this code base I found it improved performance by about 40%. If you want to use this for classification consider commenting out imshow wich takes up a lot of processing power. If you want something to view consider streaming using FFmpeg or streamed or whatever over RTSp or something. I have found, in a low powered system, getting rid of imshow increased speed by 10 times! On my desktop only by 20%. Then again with my desktop I was streaming to three different machines and saving video to another machine.

**Comment by bertelschmitt** [comment]
Saving the captured frame before handing it to yolo is absolutely unnecessary, it costs a lot of time writing and reading. Always keep the image in memory until you want to save it (if you don't have to.) In comparison, displaying the image is rather benign. I use something like this to great effect:

`    vid = cv2.VideoCapture(video_path)
    while vid.isOpened():
        #grab a  frame of video
        retval, frame = vid.read()
        if not retval:  # bogus return, try again  
            continue
        # convert it so that YOLO can understand it
        frame = frame[:, :, :: 1]
        image = Image.fromarray(frame)  
       #now hand the image straight to yolo withough going to disk
        out_pred, image = yolo.detect_image(image, show_stats= False)
        #convert the image back to something we can view and save
        result = np.asarray(image)
        #now you can show the resulting image, if so inclined
        cv2.namedWindow("Whatever", cv2.WINDOW_NORMAL)
        cv2.imshow("Whatever", result)
        #or you can turn it into a new video file (which you should have previously opened)
        newvideofile.write(result[:, :, ::1])`

That's it!

If you are not interested in the frame with boxes handed back from yolo.detect_image, then you need to, as I have done, change the function to (if asked)  just return the detected labels and their coordinates. This will be part of my multi-gpu, multi-stream, multi-process rewrite I am working on. Give me another week or two for testing

**Comment by bertelschmitt** [comment]
Correction to the above: I have adapted the yolo.detect_image function to return the names and coordinates of the detected objects, and the time it took to process the image. These are returned IN ADDITION to the returned out_prediction, and image. My call looks like this:
`
out_pred, image, labels, elapsed_time = yolo.detect_image(image, show_stats= False)
`
Again, the image is returned in-memory, and there is little gained in not handing back the image in-memory. Ignore it if not used.

**Comment by bushra-hafeez** [comment]
> I am running similar code as @BonJovi1, and it is working quite well. I do it on live video coming from IP cameras in real-time. To do that, simply run
> 
> `cap = cv2.VideoCapture('rtsp://192.168.123.123:554) # or whatever the URL of the cam may be`

Hello, it's quite interesting to do it via an ip camera... I am looking forward to doing live streaming detection through ip camera. However I am completely new to this, can you provide more details about the interfacing of ip camera with raspberry pi and then it's live streaming detection? 
Thanks

**Comment by AntonMu** [comment]
This feature is now part of the official repo. To use it, use tm`Detector.py -webcam`.
