### ISSUE TITLE
Making it work on a different kind of dataset

### ISSUE THREAD

**Issue by shreyasv11** [AntonMu/TrainYourOwnYOLO#138]
I don't have an issue per say with the code. My issue is that will this model work on my dataset which has images of documents showing various kinds of forgeries and labels containing the annotations on where the forgery is in the image. Hence, the problem is not of image detection which is primarily addressed in the code and for which the pre-trained weights are trained for. Is this a good model to use on my dataset?

**Comment by AntonMu** [comment]
As long as it is an object detection problem, you should be able to use this code. You can always try to unfreeze more layers if you don't the expected result. In the extreme case of unfreezing all layers, you basically just retrain the whole architecture.

**Comment by shreyasv11** [comment]
Okay, let me try and then I would get back to you.
