### ISSUE TITLE
[Request] YOLO V4 Support

### ISSUE THREAD

**Issue by voltaxvoltax** [AntonMu/TrainYourOwnYOLO#140]
Hi!

Since Yolo V4 it's already out and more accurate, it's possible to add support for it?

Thank you.

**Comment by bertelschmitt** [comment]
I'd be interested in this also, along with bringing all the other routines to current versions. Everything getting a bit dated

**Comment by mon28** [comment]
Looking forward to this update

**Comment by JacobTheEngineer86** [comment]
Looks like YOLOv5 just got released, I'd love for support for that when the time comes.

**Comment by bertelschmitt** [comment]
Hi @JacobTheEngineer86 : There is a bit of a controversy about yolov5, and I'd suggest to let that settle. I'd be very happy if we could get to yolov4, and bring all the other versions up to modern times while we are @ it.  There doesn't seem to be a big jump from yolov4 to alleged yolov5 anyway.

**Comment by JacobTheEngineer86** [comment]
@bertelschmitt Makes sense, thank you.

**Comment by ialci** [comment]
Looking forward for this! Are there any updates coming soon?

**Comment by AndrewW-GIT** [comment]
Probably over simplifying it, but if the convert.py converts to Keras format, is it not just a case of using a different conver.py (available from github) or have I over simplified it ?
