### ISSUE TITLE
Small Objects, No Detection

### ISSUE THREAD

**Issue by celcof** [AntonMu/TrainYourOwnYOLO#142]
### System information
- **What is the top-level directory of the model you are using**: TrainYourOwnYOLO/
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows, Anaconda
- **TensorFlow version (use command below)**: 1.13.1
- **CUDA/cuDNN version**: -
- **GPU model and memory**: Intel (R) UHD Graphics 620, 3.9 GB
- **Exact command to reproduce**: Detector.py

### Describe the problem
Hello,
Thank you for your work, simple and effective.
I am using your repository for trying to detect objects that are quite small, and, although I receive no error from the beginning to the end, when I test, the results are quite unsatisfactory. In fact, with a threshold of 0.5 no boxes are found, and I have to lower the threshold a lot (to around 0.01) to end up with some boxes. Please also take into account that I have many classes, 43, and in total I'm training on 50 images per class, I don't know if that's too few of them. I was suggested that a possible issue may be with the anchor boxes, is it possible? It's not clear to me whether I am adapting the size of my anchor boxes to the size of the objects I am trying to predict or I am using a predefined size (like the one from Pascal VOC, where objects are bigger).
Thank you very much for your help.

**Comment by AntonMu** [comment]
Hi @celcof - can you share more specifics about your training. Maybe post some logs and also a sample of the type of objects you are training on.

**Comment by bertelschmitt** [comment]
@celcof:  When detection results are sub-par, one of the first steps to take is to throw more training images at the problem. 50 images per class is quite small
