### ISSUE TITLE
Multi-class training

### ISSUE THREAD

**Issue by armansamimi** [AntonMu/TrainYourOwnYOLO#145]
1. how can i train multi-class with this code?
2. how can i use GPU instead of CPU for training?

please tell me exact steps because i am so amateur in this journey.
Thanks for your help.

**Comment by AntonMu** [comment]
Hi @armansamimi - my first recommendation would be to study the readme carefully. https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/README.md 

If you follow it it should solve your problems. Good luck!

**Comment by bushra-hafeez** [comment]
Hello,
I want to know what classifier is used here?
TIA

**Comment by armansamimi** [comment]
> Hi @armansamimi - my first recommendation would be to study the readme carefully. https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/README.md
> 
> If you follow it it should solve your problems. Good luck!

Thanks so much @AntonMu 
actually i read all the readme.md, but nowhere talked about Multi-class training and Run On GPU,
could you please help me how can i do these things?

Best regard

**Comment by vihari1729** [comment]
You Just need to use the same single class training for multi class training. When you are doing the annotation part  for your dataset, from the readme.md you just need to add the tag in the right side top part of different classes and generate the boxes in the image,after creating the project. The code will take part of classes and filters.
