### ISSUE TITLE
Training part of the keras custom model

### ISSUE THREAD

**Issue by vihari1729** [AntonMu/TrainYourOwnYOLO#147]
@AntonMu I just followed the readme .md and did the training . I am getting results for both images and videos for multiple classes.
But when I am applying it for tracking with deepsort, I am getting errors. There is a train.py file in your src folder.I think you might have taken from here https://github.com/Ma-Dan/keras-yolo4. They were telling me to use the train.py and apply it on tracking.

My question is Do i get different keras model if i train from src/keras_yolo3/train.py or same as Train_YOLO.py?

**Comment by bertelschmitt** [comment]
@vihari1729 , the train.py in the src folder is based on yolo3, and it is not the same as in  [https://github.com/Ma-Dan/keras-yolo4](https://github.com/Ma-Dan/keras-yolo4), which is for yolo4. The models are not interchangeable/
