### ISSUE TITLE
Default Grid Size

### ISSUE THREAD

**Issue by LarsNeR** [AntonMu/TrainYourOwnYOLO#148]
I have one question about the code. 

In every tutorial (like [this](https://github.com/pjreddie/darknet/wiki/YOLO:-Real-Time-Object-Detection) one) they are talking about dividing the image into cells (or a SxS grid). I would like to know how many cells your YOLO implementation creates. In the [darknet repo](https://github.com/pjreddie/darknet/issues/1042) they are talking about something like 7x7 as default. I could not find any information about that in your code and is it easily possible to change the grid size?

**Comment by AntonMu** [comment]
Hi! The grid size is defined here https://github.com/AntonMu/TrainYourOwnYOLO/blob/34fae9192f1a03d9f456f8c66aa78279d7acaee3/2_Training/src/keras_yolo3/yolo3/model.py#L144. I wouldn't recommend changing it unless you really understand all the other changes that this change would entail.
