### ISSUE TITLE
Createing Confusion matrix

### ISSUE THREAD

**Issue by lrscse** [AntonMu/TrainYourOwnYOLO#155]
Hi @AntonMu  is there possibility to create confusion matrix fir we used for more than two classes for custom dataset?

**Comment by robisen1** [comment]
Look at sklearn. Its pretty easy, just a few lines, of code you need to add to train. here is a example https://gist.github.com/RyanAkilos/3808c17f79e77c4117de35aa68447045

**Comment by lrscse** [comment]
Hi @AntonMu  @robisen1  can you guys tell me how to unfreeze more layers like 5 layers in stage 1?
