### ISSUE TITLE
Error suppression help

### ISSUE THREAD

**Issue by bertelschmitt** [AntonMu/TrainYourOwnYOLO#156]
Hi, all

I’m in (hopefully) the last phases of the multi-stream, multi-GPU project (the last 20% of a software project always take 80% of the time.)
I need a little help with error suppression. As we all know, there is a row of errors and warnings at startup we have learned to ignore. I’m running now 30 YOLO processes (on 3 GPUs) in parallel, which results in 30 times the messages. What a mess!
I need help with:
-	Suppression of errors and warnings by Keras/Tensorflow, stuff like
`WARNING:tensorflow:From /usr/local/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating: Use tf.where in 2.0, which has the same broadcast rule as np.where`
 
-	Suppression of errors and warnings by CV2, mostly errors when capabilities are interrogated,stuff like
`VIDEOIO ERROR: V4L2: property unknown is not supported
VIDEOIO ERROR: V4L2: property autofocus is not supported
VIDEOIO ERROR: V4L2: property unknown is not supported`
-	Suppression of errors emitted by the Audio driver when I’m checking whether audio is operable, stuff like:
`Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock`
 
The Keras/Tensorflow errors can be eliminated by following the suggestions and editing the files in the site packages, but this would need to be done on every computer, and it would be overwritten by the next update.
Please help. This is the last “to-do” on my list, and I’d like to proceed to cleanup, testing, and sending it to you.  I have spent a lot of time on 1700+ lines of code for a new multi-stream, multi-gpu and multi-process version of detect_video, and it is running great. 

Thank you!!!
Best, B

**Comment by AntonMu** [comment]
Hi @bertelschmitt 

Thank you for putting in the 80%!

I added some code to suppress warnings shown by the original training script: https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/Train_YOLO.py#L149-L152 

You can try a similar code to suppress the remaining warnings. 

Hope this helps!

**Comment by bertelschmitt** [comment]
Thank you! I'll try that.  I'm working with something similar in the main driver program, but haven't added it to YOLO. Will do!
The audio errors are under control.  The VIDEOIO errors are obstinate. 

Best, B

**Comment by bertelschmitt** [comment]
Hi, @AntonMu 

I stuck a call to

`
def silence():

    tf.logging.set_verbosity(tf.logging.ERROR)

    tf.autograph.set_verbosity(0)

    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

    warnings.filterwarnings("ignore")`

into   def __init__(self, **kwargs) of the YOLO class, and now there is silence!   Thank you!

B

**Comment by bertelschmitt** [comment]
OK, I have completely silenced the whole detection process, except for a solitary "Using TensorFlow backend"  that comes somewhere from the depths of YOLO. I also introduced a "hush" flag that allows to switch the noise on and  off.

B
