### ISSUE TITLE
FileNotFound error in colab

### ISSUE THREAD

**Issue by bushra-hafeez** [AntonMu/TrainYourOwnYOLO#160]
Hi, 
I'm following the guidelines of Copy of TrainYourOwnYOLO in Google Colab and having file not found issues while running Train_YOLO.py although I had mounted the drive successfully yet I get FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My'
Also, I'm a beginner in Colab and want to know how do I specify the locations of training and testing images as command line arguments when running Train_YOLO.py and Detector.py scripts?

**Comment by AntonMu** [comment]
Hi!

I recommend to fill out an issue template - and check out the troubleshooting section. Your first problem is related to the filename [containing a space](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting). 

For your second problem you can use Linux type commands such as `%ls` to get a better idea of the folder structure. Your Google drive content should be available at `/content/drive/...`.  

Hope this helps!
