### ISSUE TITLE
Prediction Error

### ISSUE THREAD

**Issue by Karthik-U-94** [AntonMu/TrainYourOwnYOLO#161]
In Inference,after running **Detector.py** we are getting only 20(max) predicted objects for every input. where there are nearly 30-40 objects of the same class.

FYI,The score while Detection is 0.20

**Comment by AntonMu** [comment]
Hi @Karthik-U-94 

Yolov3 is not designed to handle so many objects in one day image. I recommend to split your image into smaller sub images and run the model on each of them and then piece it back together.

**Comment by Karthik-U-94** [comment]
Hi @AntonMu 
Thanks for the response. I will check on it.
