### ISSUE TITLE
train and test data split

### ISSUE THREAD

**Issue by shahzaibraza37** [AntonMu/TrainYourOwnYOLO#165]
** System information**
What is the top-level directory of the model you are using:
TrainYourOwnYOLO/
Have I written custom code (as opposed to using a stock example script provided in the repo):
No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows Ananconda Prompt Python
TensorFlow version (use command below): 1.13
CUDA/cuDNN version: 10.0
GPU model and memory: NVIDIA GeForce GTX 1050 Ti and
Exact command to reproduce: NA

Describe the problem/Help

Hi,

I have querry regarding train and test data. Do you know what is split between test and train data. It is 80/20 or what? Moreover, do you know where to find in the code the test and train data split?

**Comment by robisen1** [comment]
In Train_YOLO.py you should see something like     parser.add_argument(
        "--val_split",
        type=float,
        default=0.1,
        help="Percentage of training set to be used for validation. Default is 10%.",
    ) 
at around line 116 https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/Train_YOLO.py. You can use the command line or change the default. i use 20% but the default is 10%
