### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by seba5496** [AntonMu/TrainYourOwnYOLO#167]
Hey there, i've been getting this error when trying to run Train_YOLO.py, 

![image](https://user-images.githubusercontent.com/47981550/90992963-d926e180-e580-11ea-8033-eb75837a8601.png)

System Info: 
- Windows 10 20H2 19042.450
- No GPU, No CUDA
- Tensorflow v1.15.0-92-g5d80e1e8e6 1.15.2

I think it may be caused because the training images don't match with the dataset list inside data_train.txt, but I made sure that all files listed are inside the training images folder.
The only thing I'm doing different is the annotation step, which is done with VGG Image Annotation, and I transform the output format to the Vott annotation format (CSV file), and run the Convert_to_YOLO.py script in 1_Image_Annotation, I'll put said script at the end.

`import os, random, shutil
import pandas as pd
cwd = os.getcwd()
data_folder = cwd
img_folder = os.path.join(data_folder, 'Dataset')
img_list = os.listdir(img_folder)

training_folder = os.path.join(data_folder, 'Training_Images', 'vott-csv-export')
test_folder = os.path.join(data_folder, 'Test_Images')

if len(img_list) == 0:
    print("Dataset folder is Empty'\n Reseting folders states")
    for i in os.listdir(training_folder):
        if i[-4:] == '.jpg':
            shutil.move(os.path.join(training_folder, i), os.path.join(img_folder, i))
    for i in os.listdir(test_folder):
        shutil.move(os.path.join(test_folder, i), os.path.join(img_folder, i))
    for i in os.listdir(os.path.join(data_folder, 'val')):
        shutil.move(os.path.join(data_folder, 'val', i), os.path.join(img_folder, i))

else:
    print("The Data folder has {} images...".format(len(img_list)))
    if input('Do you want to reset folder state? (Y or N)\n') == 'Y' or 'y':
        for i in os.listdir(training_folder):
            if i[-4:] == '.jpg':
                shutil.move(os.path.join(training_folder, i), os.path.join(img_folder, i))
        for i in os.listdir(test_folder):
            shutil.move(os.path.join(test_folder, i), os.path.join(img_folder, i))
        for i in os.listdir(os.path.join(data_folder, 'val')):
            shutil.move(os.path.join(data_folder, 'val', i), os.path.join(img_folder, i))

img_list = os.listdir(img_folder)

for i in random.sample(img_list, 100):
    shutil.move(os.path.join(img_folder, i), os.path.join(data_folder, 'val', i))
print("100 images reserved for validation")

print("The Data folder has {} images...".format(len(img_list)))

img_list = os.listdir(img_folder)
training_size = input("Set the Training Size in %... NOTE --> The rest of the images will be used as the test set:\n")
training_size_calc = round((int(training_size)/100)*len(img_list))
test_size = len(img_list) - int(training_size_calc)

print("{inputed_val} percent of {dataset_size} is --> {percentage_calc}".format(inputed_val = training_size, dataset_size=len(img_list), percentage_calc=training_size_calc))
print("The test set is --> {test_set_val}".format(test_set_val=test_size))

img_list = os.listdir(img_folder)

list_of_images = []
csv_data = {'image':[], 'xmin':[],'ymin':[],'xmax':[],'ymax':[],'label':[]}
#left, top, right, bottom
with open(os.path.join(os.getcwd(), 'dataset.txt'), 'w') as data_file:
    for i in random.sample(img_list, training_size_calc):
        ground_truth_file = os.path.normpath(os.path.join(r'C:\Users\Sebastian\OneDrive\_Coding_\OPAYN\Dataset\V1_Base\ground_truth', i.replace('.jpg', '.txt')))
        try:
            with open(ground_truth_file, 'r') as f:
                file_lines = f.readlines()
                for lines in file_lines:
                    line = lines.split()
                    file_name = i
                    csv_data['image'].append(file_name)
                    label = line[0]
                    csv_data['label'].append(label)
                    left = int(line[1])
                    csv_data['xmin'].append(left)
                    top = int(line[2])
                    csv_data['ymin'].append(top)
                    right = int(line[3])
                    csv_data['xmax'].append((right+left-1))
                    bottom = int(line[4])
                    csv_data['ymax'].append((bottom+top-1))
            for line in file_lines:
                data_file.write(i + ' '+ line)
            shutil.move(os.path.join(img_folder, i), os.path.join(training_folder, i))
        except FileNotFoundError:
            print('{a} not found in {b}'.format(a = i, b = ground_truth_file))
dataframe = pd.DataFrame(csv_data)
dataframe.to_csv('csv.csv')
img_list = os.listdir(img_folder)
for i in random.sample(img_list, test_size):
    shutil.move(os.path.join(img_folder, i), os.path.join(test_folder, i))

img_list = os.listdir(img_folder)
print("\nNow the Data folder has {} images...".format(len(img_list)))

val_folder = os.path.join(data_folder, 'val')

print('Training folder has: {train} images\nTest folder has: {test} images\nValidation folder has: {val}'.format(train=(len(os.listdir(training_folder))-2), test=len(os.listdir(test_folder)), val=len(os.listdir(val_folder))))`

Thanks in advance...

**Comment by pascalfavre** [comment]
Hello @seba5496,
I had the same issue this morning. The problem is that the script Train_Utils looks for data in the "TrainYourOwnYOLO" Folder. As your project is not in a so named folder it throws an error. You can either change the default name in the Train_Utils script or rename the base folder for your project.

**Comment by seba5496** [comment]
> Hello @seba5496,
> I had the same issue this morning. The problem is that the script Train_Utils looks for data in the "TrainYourOwnYOLO" Folder. As your project is not in a so named folder it throws an error. You can either change the default name in the Train_Utils script or rename the base folder containing your project.

Yey! It worked, thank you very much, sorry it took me so long to answer, have a great day :)
