### ISSUE TITLE
Inference slow with CPU

### ISSUE THREAD

**Issue by YannickLecroart** [AntonMu/TrainYourOwnYOLO#170]
Hi Anton,

First or all, congratulations for all the work. I have trained my own custom model on CPU (my own laptop with a Core i5 configuration as my graphic card is a Radeon). While processing an image I can only get 0.7 at best. Would the same model be more accurate or run faster on the same laptop if I train it on CPU with AWS for instance ?

Thanks in advance.

Regards,

**Comment by AntonMu** [comment]
Hi @YannickLecroart,

Glad you were able to train your own model! When you say 0.7 - do you mean 0.7 fps? If so, that is about expected for this model. Training somewhere else will not make inference faster. To get better accuracy you can try to train longer (you can use the colab notebook to speed things up) or label more training images.

Hope that helps!

**Comment by YannickLecroart** [comment]
Yes I meant 0.7 FPS. So if I understand correctly if I want to get better faster the only option I have right now is to run the model on a device with a good GPU (Nvidia with CUDA support for instance)? Sorry to bother you with all these questions.

**Comment by AntonMu** [comment]
Correct. Another option would be to use the tiny version but then you would have worse predictions.

**Comment by MostafaAlli** [comment]
Hi Anton,

I have got an issue with the multu_GPU_model. 

I have an onboard nVidia card which isn't counted as a GPU but I got a Check_Failed: Cuda_SUCCESS (0 vs. 303).

Can you let me know how to fix this? I actually dont want to recall GPU devices and when I run your codes using anaconda, it seems the GPU is ignored but then shortly after that I get the above mentioned error.
