### ISSUE TITLE
Error in Train_YOLO.py after recent update - Failed to get convolution algorithm 

### ISSUE THREAD

**Issue by RobinV760** [AntonMu/TrainYourOwnYOLO#173]
I didn't adjust anything in the script yet, just wanted to try out the new updates that were made a few days ago. Got this error when running Train_YOLO.py.

tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node functional_5/conv2d/Conv2D (defined at Train_YOLO.py:230) ]] [Op:__inference_train_function_22034]

Function call stack:
train_function

**Comment by AntonMu** [comment]
Hi @RobinV760,

When using the tf2.3 version, you need a higher CUDA version, see here: https://www.tensorflow.org/install/source#linux.

If you don't want to mess around with your current CUDA installation, you can check out the `v0.1.15` [tag](https://github.com/AntonMu/TrainYourOwnYOLO/releases/tag/v0.1.15) which is the state of the repo before the switch to tf2.3.

**Comment by Desmond00** [comment]
Hello @AntonMu,

With the latest release with tf2.3 facing the same issue. 
https://www.tensorflow.org/install/source#linux, here they have mentioned for CUDA10.1 with tf2.3.
But with the required config for CUDA10.1 still facing the same issue.

**Comment by AntonMu** [comment]
Hi @Desmond00,

Handling CUDA and reinstalling and updating it is pretty messy. I recommend to use the last version (v0.1.15) that works with your previous CUDA version. You can checkout the tag as mentioned before. Another option is to use Colab which is also Linux based and already has the right drivers installed.
