### ISSUE TITLE
Mismatch between model and given anchor and class sizes

### ISSUE THREAD

**Issue by jsphar** [AntonMu/TrainYourOwnYOLO#177]
**Readme** 
- I have followed all Readme instructions carefully word by word: Yes

**System information**
- **What is the top-level directory of the model you are using**:TrainYourOwnYOLO-master - Utilizing the tutorial [https://github.com/AntonMu/TrainYourOwnYOLO](url)
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: I am using a virtual environment via Powershell on my Windows PC with Windows 10 Pro, Version 1909, Intel Core i7 with 16 GB Ram.  
- **TensorFlow version (use command below)**: I believe 2.3 -  I used the install command in PowerShell within the virtual env on my PC by running the command - pip install -r requirements.txt - this was after downloading the repo 
- **CUDA/cuDNN version**: I am unsure of the version
- **GPU model and memory**: I am unsure of this.  
- **Exact command to reproduce**: I found the following error after running the last step of the tutorial using the Detector.py:

**Describe the problem**
I am running the Detector.py script to test my sample images, I only have about 10 images and 1 type of object I am trying to detect.  I was successful in running the previous steps in the downloading the weights and training the model.  For some reason I have two h5 files, one called yolo.h5 and one called trained_weights_final.h5.  Originally only the yolo.h5 had info in it I am guessing because of it's size.  I did try to rename yolo.h5 file to trained_weights_final.h5 since it seems that the script was looking for that file name.  

I have also tried changing the classes to classes_path like suggested in this post -- [https://github.com/qqwweee/keras-yolo3/pull/301](url) but that didn't seem to fix the problem.  

The main error that is returned is the following:
_To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-14 22:55:36.615331: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2a913f30420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-14 22:55:36.621463: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-14 22:55:36.632791: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-14 22:55:36.636716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]
Traceback (most recent call last):
  File "Detector.py", line 194, in <module>
    "model_image_size": (416, 416),
  File "D:\GIS\ObjectDetection\TrainYourOwnYOLO-master\2_Training\src\keras_yolo3\yolo.py", line 50, in __init__
    self.boxes, self.scores, self.classes = self.generate()
  File "D:\GIS\ObjectDetection\TrainYourOwnYOLO-master\2_Training\src\keras_yolo3\yolo.py", line 95, in generate
    ), "Mismatch between model and given anchor and class sizes"
AssertionError: Mismatch between model and given anchor and class sizes_

@AntonMu  - sorry for not filling out the issue with all the proper information, I have added in some more information here that I hope diagnoses the problem better.  Again, I am just trying to get a feeling of some small results to understand how this works. The photo total I am use is really low which I understand I would need more and I am only trying to identify one concept,  I am not sure if this the error or it is caused by the possibility that the model was not trained properly in the first place.

Any help you could offer would be greatly appreciated.

Thanks, Jason

**Comment by AntonMu** [comment]
Hi @jsphar,

Have a look at the troubleshooting section (point 1). If you use the original folder structure and retry it, you should be good. 

Hope this helps!

Anton
