### ISSUE TITLE
Plotting the ROC/AUC Curves

### ISSUE THREAD

**Issue by bushra-hafeez** [AntonMu/TrainYourOwnYOLO#180]
Hey, I have trained the model many times on my dataset with a lot of issues that were resolved within hours, a big thanks for all the help.
I was wondering it would be quite nice and helpful for everyone to observe the ROC/AUC curves in order to have a better idea of classifiers excellency. I am thinking about arranging the False positives in a separate folder from test images but a little confused about how to plot the ROC curve by doing that.

**Comment by AntonMu** [comment]
Hi - since this is an object detection problem the terms AUC and ROC don't make sense. They are specific to binary classification. Here, the right metric is mAP. See #215 for more information.
