### ISSUE TITLE
Paths for images get messed up

### ISSUE THREAD

**Issue by MostafaAlli** [AntonMu/TrainYourOwnYOLO#184]
Before filing a report consider the following two questions:

### Have you checked the [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section? YES

Once you are familiar with the code, you're welcome to modify it. Please only continue to file a bug report if you encounter an issue with the provided code and after having followed the instructions.

If you have followed the instructions exactly, couldn't solve your problem with the provided troubleshooting tips and would still like to file a bug or make a feature requests please follow the steps below.

1. It must be a bug, a feature request, or a significant problem with the documentation (for small docs fixes please send a PR instead).
2. **Every section** of the form below must be filled out.

------------------------

### Readme 

- I have followed all Readme instructions carefully: YES

### Troubleshooting Section

- I have looked at the  [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section: YES

### System information
- **What is the top-level directory of the model you are using**:G:\TrainYourOwnYolo
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 7
- **TensorFlow version (use command below)**: 1.14
- **CUDA/cuDNN version**: Dont have GPU 
- **GPU model and memory**: Dont have GPU
- **Exact command to reproduce**: Python train_yolo.py

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
I have followed your instruction like what you said. I use Anaconda. As I run "Python train_yolo.py" from :G:\TrainYourOwnYolo\2_Training\" the paths for images get this part concatenated to the rest of its path with TrainYourOwnYolo in the middle. I have looked at your code and I know you have a function to convert files to system machine path but I have no idea why this happens

### Source code / logs
![error](https://user-images.githubusercontent.com/70396162/93795951-01206800-fc47-11ea-9649-a5397bd1ffd5.png)

**Comment by bushra-hafeez** [comment]
I had same file not found errors and then I noticed that it usually occured if I had images names containing spaces.. so try to give them names like image_20.jpg instead of image (20).jbp

**Comment by MostafaAlli** [comment]
I am using the original image lists as the repo. I didnt use my own photos.
________________________________

**Comment by MostafaAlli** [comment]
> 
> 
> I had same file not found errors and then I noticed that it usually occured if I had images names containing spaces.. so try to give them names like image_20.jpg instead of image (20).jpg

I am using the original image lists as the repo. I didnt use my own photos.

**Comment by bushra-hafeez** [comment]
Your folder structure has been changed ... You have another TrainYourOwnYolo folder within 2_Training folder.. Thats causing the problem according to troubleshooting, check it out 
https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting

**Comment by MostafaAlli** [comment]
> 
> 
> Your folder structure has been changed ... You have another TrainYourOwnYolo folder within 2_Training folder.. Thats causing the problem according to troubleshooting, check it out
> https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting

Sir that is incorrect, yo ujsut need to read the code and you will see "TrainYourOwnYolo" is made by the Anton as a function argument in ConvertToTheMachine Function for conversion and I have no other extra folder. If you have no familarity with the project, please do not waste my time

`def ChangeToOtherMachine(filelist, repo="TrainYourOwnYOLO", remote_machine=""):
    """
    Takes a list of file_names located in a repo and changes it to the local machines file names. File must be executed from withing the repository

    Example:

    '/home/ubuntu/TrainYourOwnYOLO/Data/Street_View_Images/vulnerable/test.jpg'

    Get's converted to

    'C:/Users/Anton/TrainYourOwnYOLO/Data/Street_View_Images/vulnerable/test.jpg'

    """
    filelist = [x.replace("\\", "/") for x in filelist]
    if repo[-1] == "/":
        repo = repo[:-1]
    if remote_machine:
        prefix = remote_machine.replace("\\", "/")
    else:
        prefix = ((os.getcwd().split(repo))[0]).replace("\\", "/")
    new_list = []

    for file in filelist:
        suffix = (file.split(repo))[1]
        if suffix[0] == "/":
            suffix = suffix[1:]
        new_list.append(os.path.join(prefix, repo + "/", suffix).replace("\\", "/"))
    print(
        "8888888888888888888*********************************98888888888888888888888888888888888"
    )
    print(new_list)
    return new_list`

**Comment by MostafaAlli** [comment]
I dont even touch anything. simply unzipping and running your code. What troubleshooting. God~!!

**Comment by AntonMu** [comment]
@MostafaAlli your behavior is completely out of line. I'm closing the issue here. You should try follow the provided instructions.
