### ISSUE TITLE
Training on huge dataset in chunks

### ISSUE THREAD

**Issue by bushra-hafeez** [AntonMu/TrainYourOwnYOLO#185]
Hello, I want to train the model on my custom dataset which comprises of upto 40k images which is too much heavy data. Is there a way to train the model in chunks? Like i could train the model on some part of my data and next time when i start training on further data,it should add the current weights to the weights of previously trained data.
Because,due to some issues i am unable to train the model on whole dataset in one go.

**Comment by bushra-hafeez** [comment]
Hi @AntonMu 
Can you explain what does the file checkpoint.h5 do? 
Does it save the model weights? 
And does that mean when I start training on colab, it will start from where it left off? 

It would be quite helpful for me to know this

**Comment by AntonMu** [comment]
Hi @bushra-hafeez 

40k images is not very big for a neural network - in fact, the original weights are trained on many million images. 

If there is any way I recommend to try to train it on all data. During training, the algoritm will only use a batch of your data to update the weights. Thus, the computational power required is not larger if you train on more images. 

In principal, you could train it on a subset and then save the weights and then train on the next subset and so on. Just remember that one iteration through all your data is just a single epoch, so you would have to do this process 100 times. 

What does not work, however, is to fully train the network on say 10% of your images and then use these weights to fully train it on the next 10% and so on. When you restart, the network will forget most of the things it had just learned.

**Comment by bushra-hafeez** [comment]
> Hi @bushra-hafeez
> 
> 40k images is not very big for a neural network - in fact, the original weights are trained on many million images.
> 
> If there is any way I recommend to try to train it on all data. During training, the algoritm will only use a batch of your data to update the weights. Thus, the computational power required is not larger if you train on more images.
> 
> In principal, you could train it on a subset and then save the weights and then train on the next subset and so on. Just remember that one iteration through all your data is just a single epoch, so you would have to do this process 100 times.
> 
> What does not work, however, is to fully train the network on say 10% of your images and then use these weights to fully train it on the next 10% and so on. When you restart, the network will forget most of the things it had just learned.

Actually, I am training on only 2000+ images with 4 classes... there is more than one class in each image so the training samples are nearly 4000. And as I train them on colab, it takes 8+ hours to be trained and after that training fails due to GPU limitations. So if that happens just on training with 2000 images, i definitely cant train on a dataset of 40k due to these limitations. Thats why I asked if there's a way to train on chunks of data or if checkpoint.h5 file can help...

**Comment by AntonMu** [comment]
Okay - so it seems like you are limited by runtime rather than data set size. This makes a lot more sense. 

What I said before still holds then. Do not split up your training images but instead split up your training. In other words, use all images but train for fewer epochs. 

E.g. train for the first 10 epochs then save and then resume etc. You have to experiment a bit how many epochs you can train within the limit. Alternatively, you can get Colab Pro which is just $10 a month and gives you more flexibility in terms of timeouts.
