### ISSUE TITLE
How many layers are we actually training in this model while using the custom data-set?  

### ISSUE THREAD

**Issue by parikshit14** [AntonMu/TrainYourOwnYOLO#188]
### Describe the problem
Actually, there isn't any problem But I just wanted to know how many layers of this YOLO v3 architecture are we training? During downloading YOLO weights it only shows trainable and non-trainable parameters but the layers to be trained is not specified

**Comment by AntonMu** [comment]
There are two stages. In the first 51 epochs (by default), only the output layers are unfrozen, and in the second stage, for another 51 epochs (by default), all layers are unfrozen to fine-tune the model.

To learn more, I encourage you to look at the [training script](https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/Train_YOLO.py).

Hope this helps!

**Comment by parikshit14** [comment]
ok, thanks for the info.
