### ISSUE TITLE
Download_and_Convert_YOLO_weights.py doesn't handle paths with whitespaces

### ISSUE THREAD

**Issue by MateusMarcuzzo** [AntonMu/TrainYourOwnYOLO#193]
Hello, I have had to choose another folder without blank spaces.

I'm on Ubuntu 18.04, and since I'm brazilian, my Desktop top folder is named "Área de Trabalho"

```
Downloading Raw yolov3.weights

python: can't open file '/home/mateus/Área': [Errno 2] No such file or directory
Downloaded Raw yolov3.weights in 0.0 seconds

2020-10-05 16:05:35.386910: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Loading weights.
Traceback (most recent call last):
  File "convert.py", line 286, in <module>
    _main(parser.parse_args())
  File "convert.py", line 85, in _main
    weights_file = open(weights_path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'yolov3.weights'

```

He thinks it's just 'Área', but its not. Moved to Documents (Documentos) and it worked.

**Comment by ForLynda** [comment]
Hello, I have same issue but I can't solve this problem.
Could you tell me what does your 'Moved to Documents (Documentos)' comment means?

**Comment by ForLynda** [comment]
> Hello, I have had to choose another folder without blank spaces.
> 
> I'm on Ubuntu 18.04, and since I'm brazilian, my Desktop top folder is named "Área de Trabalho"
> 
> ```
> Downloading Raw yolov3.weights
> 
> python: can't open file '/home/mateus/Área': [Errno 2] No such file or directory
> Downloaded Raw yolov3.weights in 0.0 seconds
> 
> 2020-10-05 16:05:35.386910: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
> Loading weights.
> Traceback (most recent call last):
>   File "convert.py", line 286, in <module>
>     _main(parser.parse_args())
>   File "convert.py", line 85, in _main
>     weights_file = open(weights_path, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'yolov3.weights'
> ```
> 
> He thinks it's just 'Área', but its not. Moved to Documents (Documentos) and it worked.

Hello, I have same issue but I can't solve this problem.
Could you tell me what does your 'Moved to Documents (Documentos)' comment means?
