### ISSUE TITLE
What kind of this error?

### ISSUE THREAD

**Issue by ezratoga** [AntonMu/TrainYourOwnYOLO#196]
file Train_YOLO.py that i run on windows command prompt. then, the output is like this:
2020-10-17 22:00:34.278367: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2020-10-17 22:00:38.077641: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
2020-10-17 22:00:38.108725: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-10-17 22:00:38.127297: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-E4UNFNB
2020-10-17 22:00:38.137317: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-E4UNFNB
2020-10-17 22:00:38.143126: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-17 22:00:38.175719: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1c9a21237d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-17 22:00:38.186929: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Create YOLOv3 model with 9 anchors and 1 classes.
Load weights D:\Compressed\TrainYourOwnYOLO-master\2_Training\src\keras_yolo3\yolo.h5.
Freeze the first 249 layers of total 252 layers.
2020-10-17 22:00:42.953924: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
8888888888888888888*********************************98888888888888888888888888888888888
['D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_%20(1).jpg 80,3,215,144,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_%20(2).jpg 59,6,174,126,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/2Q__%20(1).jpg 27,15,107,87,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/2Q__%20(2).jpg 87,2,197,124,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/2Q__.jpg 3,1,106,103,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_%20(4).jpg 96,30,151,79,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_%20(5).jpg 135,4,266,131,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_%20(3).jpg 66,49,177,153,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_%20(6).jpg 145,55,213,129,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_%20(7).jpg 81,39,180,137,0 148,0,248,101,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_.jpg 26,0,186,162,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/Z%20(2).jpg 187,0,269,70,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/Z%20(3).jpg 13,0,247,170,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/Z%20(4).jpg 80,58,185,172,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/Z%20(1).jpg 46,4,143,100,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/Z.jpg 117,22,235,127,0 6,84,104,180,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(1).jpg 9,9,195,169,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(10).jpg 56,23,119,82,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(100).jpg 109,86,154,124,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(11).jpg 123,19,193,88,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(14).jpg 7,22,195,182,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(12).jpg 95,51,186,120,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(13).jpg 68,14,183,109,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(15).jpg 28,8,138,119,0 67,55,195,193,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(16).jpg 23,8,210,181,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(18).jpg 47,5,251,168,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(17).jpg 74,12,181,98,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(19).jpg 153,2,254,100,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(2).jpg 67,16,132,77,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(20).jpg 46,26,133,107,0 132,35,213,107,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(21).jpg 17,77,102,167,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(23).jpg 175,8,228,67,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(22).jpg 150,6,226,95,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(24).jpg 80,2,225,146,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(25).jpg 56,19,146,94,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(26).jpg 82,17,177,115,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(27).jpg 44,62,207,175,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(29).jpg 29,2,180,155,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(28).jpg 163,27,278,112,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(3).jpg 13,9,108,112,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(30).jpg 122,65,159,112,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(31).jpg 153,83,180,110,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(32).jpg 142,21,222,91,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(33).jpg 129,17,289,163,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(34).jpg 65,102,85,122,0 93,81,119,104,0 124,82,149,105,0 150,84,175,107,0 180,85,206,112,0 213,95,239,118,0 243,110,262,132,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(36).jpg 77,23,170,111,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(35).jpg 46,25,145,146,0 131,8,250,128,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(37).jpg 96,10,171,74,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(38).jpg 67,20,172,111,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(39).jpg 8,10,146,123,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(4).jpg 109,27,188,98,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(40).jpg 172,3,279,109,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(42).jpg 106,7,195,87,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(41).jpg 57,40,237,170,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(43).jpg 78,38,106,73,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(44).jpg 55,5,217,177,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(46).jpg 67,56,158,118,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(45).jpg 16,17,243,187,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(47).jpg 54,5,164,101,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(48).jpg 55,42,100,87,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(49).jpg 195,41,266,101,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(50).jpg 94,21,119,47,0 180,12,203,33,0 235,14,261,37,0 105,102,131,126,0 226,103,265,148,0 52,98,76,117,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(5).jpg 109,7,212,110,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(51).jpg 20,4,118,84,0 176,46,273,168,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(52).jpg 164,27,224,84,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(53).jpg 0,0,110,101,0 155,26,286,148,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(54).jpg 39,1,205,150,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(56).jpg 63,14,179,124,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(57).jpg 121,59,188,122,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(58).jpg 76,30,225,168,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(59).jpg 95,2,171,86,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(6).jpg 74,3,131,53,0 184,56,252,113,0 133,26,190,83,0 247,21,288,73,0 11,37,62,92,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(60).jpg 122,21,251,134,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(61).jpg 170,12,238,81,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(62).jpg 99,21,156,81,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(63).jpg 46,31,130,105,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(64).jpg 111,11,218,131,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(65).jpg 52,24,131,118,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(66).jpg 94,38,188,124,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(67).jpg 76,3,190,113,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(69).jpg 54,17,238,166,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(68).jpg 119,13,244,137,0 30,23,131,125,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(7).jpg 71,20,121,65,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(70).jpg 176,7,255,98,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(71).jpg 146,0,254,116,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(73).jpg 63,0,212,131,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(72).jpg 58,5,211,154,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(74).jpg 177,54,242,113,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(75).jpg 26,29,166,148,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(76).jpg 15,6,84,82,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(78).jpg 47,22,183,150,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(77).jpg 82,63,134,120,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(79).jpg 103,5,180,56,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(8).jpg 86,0,293,163,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(80).jpg 102,65,132,103,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(81).jpg 67,1,200,147,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(82).jpg 76,16,190,138,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(83).jpg 97,5,264,166,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(84).jpg 46,7,147,99,0\n', 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(85).jpg 55,34,93,79,0 216,31,251,70,0']
Train on 90 samples, val on 10 samples, with batch size 32.
Traceback (most recent call last):
  File "train_yolo.py", line 237, in <module>
    callbacks=[logging, checkpoint],
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1829, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1063, in fit
    steps_per_execution=self._steps_per_execution)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1117, in __init__
    model=model)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 786, in __init__
    peek, x = self._peek_and_restore(x)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 843, in _peek_and_restore
    peek = next(x)
  File "D:\Compressed\TrainYourOwnYOLO-master\Utils\Train_Utils.py", line 194, in data_generator
    image, box = get_random_data(annotation_lines[i], input_shape, random=True)
  File "D:\Compressed\TrainYourOwnYOLO-master\2_Training\src\keras_yolo3\yolo3\utils.py", line 65, in get_random_data
    image = Image.open(line[0])
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2891, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(54).jpg'

I hope there will be a fast respon of this. because i didn't found a mistake on Train_YOLO.py code. thx before

**Comment by K1ndWha1e** [comment]
Dude, this means, that there no image in this directory _'D:/Compressed/TrainYourOwnYOLO/master/Data/Source_Images/Training_Images/vott-csv-export/images%20(54).jpg_', oh I see idk why but you should change master to -master, you can look up for this path  _D:/Compressed/TrainYourOwnYOLO/**-master**/Data/Source_Images/Training_Images/vott-csv-export/images%20(66).jpg_ in your message
