### ISSUE TITLE
Download_and_Convert_YOLO_weights.py does not download Test looks incorrect

### ISSUE THREAD

**Issue by AndrewW-GIT** [AntonMu/TrainYourOwnYOLO#200]
The file does Download_and_Convert_YOLO_weights.py does not do anything i.e download. When i looked at the code changing
if not os.path.isfile(os.path.join(download_folder, weights_file)):
to 
if os.path.isfile(os.path.join(download_folder, weights_file)):
 resolved the issue as the test appears to be true is all is good so will never work, removing the not makes it work

**Comment by bertelschmitt** [comment]
@AndrewW-GIT:  
```
if not os.path.isfile(os.path.join(download_folder, weights_file)) 
```
checks whether the file already is present, and when it is, it won't download it. If no file, download occurs. Your change would cause it to download if, and only if, the file is already present ... which kindof defeats the purpose. Change it back. Just tested it, it works.
