### ISSUE TITLE
Labelled using YoloLabel

### ISSUE THREAD

**Issue by ajaysurya1221** [AntonMu/TrainYourOwnYOLO#202]
Hi, I labelled my data using YoloLabel and it contained only .txt files for each image and no CSV. Any way I could use that data, please?

**Comment by AntonMu** [comment]
Hi @ajaysurya1221 - yes you can use your own data for sure. You need to make sure you match the [data_train.txt]( https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/Data/Source_Images/Training_Images/vott-csv-export/data_train.txt) file. Each line has the pathname of the image and then for each box there are 5 values, the first four are the location of the box and the last is the class id.

**Comment by ajaysurya1221** [comment]
thank you so much for your time and support.
