### ISSUE TITLE
Bad GPU utilization while training

### ISSUE THREAD

**Issue by DefinitlyNotAHackerTrustMeIAmADolphin** [AntonMu/TrainYourOwnYOLO#203]
windows 10
python 3.6
tensorflow-gpu==1.14
GPU: Nvidia GTX 2080 ti
CPU: Intel Xeon E5-2680 v4 14 core 2,4ghz
Cuda 10

I am using the SVHN Dataset with Annotations as proposed in [this](https://github.com/MrEliptik/YOLOv3_digits) repo.
it contains 33000 training images of housnumbers.

I left most of the code vanilla, but i'm getting bad GPU utilization. while training i have 60% cpu usage and then every 3 Seconds the gpu ramps up to 30 percent for a second.
I did some research and i'm getting the suspicion that the data generator is the bottleneck.
I see people using multiple GPUs, hows that possible? Or am i just running the wrong TF and Cuda version?

edit: the estimated time per epoch is 50 minutes, even on my lower spec PC with 4 core, gtx 1080 i get the same eta.

**Comment by AntonMu** [comment]
You should check which version you are using. The latest version is for tf2. There is some earlier versions for tf1 which you could try. You can find it under releases. Generally, I recommend to use the latest version but then you also need to update your cuda.

**Comment by DefinitlyNotAHackerTrustMeIAmADolphin** [comment]
Thank you for your reply.
I just went through all the trouble of upgrading CUDA on my 'smaller' machine.
It has pretty much the same result. 
Almost 1 hour per epoch on the GTX1080.
Do you have any other suggestions on what to tweak?

**Comment by AntonMu** [comment]
Did you follow the steps in the [requisites](https://github.com/AntonMu/TrainYourOwnYOLO#requisites)? Specifically, making sure that you have the [right versions](https://www.tensorflow.org/install/source_windows#gpu).

**Comment by DefinitlyNotAHackerTrustMeIAmADolphin** [comment]
Yes, I have followed all the steps, with a new Environment and the installing the requisites straight from the file. So that shouldn't be an issue. 
I'm getting strange errors now like:
`2020-11-20 23:21:43.182434: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] layout failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-11-20 23:21:43.227386: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
2020-11-20 23:21:43.585513: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:581] remapper failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)`

i tried different batch sizes, but not much changes. with a low batch size i get higher GPU utilization but it takes longer per epoch.

**Comment by AntonMu** [comment]
Since tf1.16ish there is no need to install tensorflow-gpu anymore. I would like to emphasize that this code has been tested with GPUs on Windows as is. Try to run it out of the box (no code changes) and see if it works to debug your system. Any code changes will put you in uncharted territory.
