### ISSUE TITLE
Annotation issue

### ISSUE THREAD

**Issue by ajaysurya1221** [AntonMu/TrainYourOwnYOLO#206]
Hi, 

I trained my dataset with YoloLabel and I found out that it has only .txt output for each file. 1000 jpg images and 1000 .txt files.

I wrote a script to append those to CSV but still, I'm facing another issue.

the values produced in the .txt file is : (for 1 image with 4 classes)

0 0.485048 0.334155 0.253589 0.059186 #format : class center_x center_y width height
1 0.449761 0.529593 0.180622 0.060419
2 0.437799 0.739211 0.153110 0.053021
3 0.550239 0.215783 0.250000 0.054254

is there anything I can do to use this data to train with TrainYourOwnYolo?

**Comment by AntonMu** [comment]
Hi - please have a look at this comment https://github.com/AntonMu/TrainYourOwnYOLO/issues/202#issuecomment-730861605 you need to match the format of the `.txt` file. There is no need to create `.csv` files. In  your example, your format is different.
