### ISSUE TITLE
param --weights_path ignored

### ISSUE THREAD

**Issue by Superxwolf** [AntonMu/TrainYourOwnYOLO#209]
Currently `2_Training\Train_YOLO.py ` takes in the arguments `--weights_path`, but doesn't actually use it for creating the model, always uses the default weight path. Seems like it was removed [here](https://github.com/AntonMu/TrainYourOwnYOLO/commit/63234a81efa7f99b0fa44b300741a38b5b67f832#diff-8299a3bf7bbe39b0e3a0e45b1d88be666ba5d6fa784f096b5c1fbd229f841dbbL162).

It was very weird to pass in a weight to continue training, only to see the first epoch to have almost 2k loss.

**Comment by AntonMu** [comment]
Hi @Superxwolf - thanks for spotting this. Feel free to make a PR to fix it. Thanks!

**Comment by Superxwolf** [comment]
PR made: #210
