### ISSUE TITLE
Question: Is it better to annotate cropped images, or larger uncropped ones?

### ISSUE THREAD

**Issue by bentwookie** [AntonMu/TrainYourOwnYOLO#211]
Apologies if I'm not asking this question in the right place.

I've been building a system which discourages the feral cats pooping in my flower beds through the means of YOLO and a garden hose. 

The images come off several IP cameras and are quite large. I have an up front mechanism that looks for motion and grabs interesting frames to annotate. It can record the entire frame, or just crop to the area of motion.

My question: Is it more accurate to annotate the full images in vott or to annotate the tighter cropped versions? I'm about to annotate a ton of them and want to do it right the first time :)

Thanks for your advice, and for making YOLO nicely approachable!

**Comment by AntonMu** [comment]
Hi @bentwookie - that sounds like a fun project!

My advice would be to train on the same type of images that you are later going to feed to the model. If the model only receives the cropped photos, you should train on them. One thing to note is that yolo will downsample your images to 416x416 pixels. So if your object gets too small, the model will have trouble picking it up.

**Comment by bentwookie** [comment]
I'll try and make my crop 416x416 and see how that goes. Thanks for the advice!

**Comment by AntonMu** [comment]
Oh - you don't need to crop your images to a specific size. The code will do that automatically for you! Feel free to give it images of any size. Just be aware that if you have a gigantic image, the model will struggle to pick out something in a very small area.
