### ISSUE TITLE
Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.

### ISSUE THREAD

**Issue by ravichopra0107** [AntonMu/TrainYourOwnYOLO#212]
Before filing a report consider the following two questions:

### Have you looked for [similar issues](https://github.com/AntonMu/TrainYourOwnYOLO/issues?q=is%3Aissue)? 

Once you are familiar with the code, you're welcome to modify it. Please only continue to file a bug report if you encounter an issue with the provided code and after having followed the instructions.

If you have followed the instructions exactly, couldn't solve your problem with the provided troubleshooting tips and would still like to file a bug or make a feature requests please follow the steps below.

1. It must be a bug, a feature request, or a significant problem with the documentation (for small docs fixes please send a PR instead).
2. **Every section** of the form below must be filled out.

------------------------

### Readme 

- I have followed all Readme instructions carefully: YES

### Troubleshooting Section

- I have looked at the  [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section: YES

### Troubleshooting Section

- I have looked for [similar issues](https://github.com/AntonMu/TrainYourOwnYOLO/issues?q=is%3Aissue): Found a similar issue but in that case, the error pops up after the training.

### System information
- **What is the top-level directory of the model you are using**: TrainYourOwnYOLO/
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: Little changes in paths
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 20.04
- **TensorFlow version (use command below)**: 2.3.1
- **CUDA/cuDNN version**: 10.1.0/7.6.5
- **GPU model and memory**: NVIDIA GTX 1650 4GB
- **Exact command to reproduce**: python Train_YOLO.py
- **Python version**: 3.7

You can obtain the TensorFlow version with

`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug or a feature request.
Problem: I am experiencing this error when I try to train my model on GPU. It trains perfectly on CPU. At first, the CUDA is loaded but then training does not starts and the command exited with the error stated above. I also tried to train some other model to verify its an issue with my CUDA/cuDNN versions. But it trained perfectly, so my version is not broken.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.
![Screenshot from 2021-01-08 21-31-36](https://user-images.githubusercontent.com/56033256/104036107-02c36b00-51f9-11eb-9eef-67bdbedaf8bf.png)

**Comment by AntonMu** [comment]
see #181

**Comment by ravichopra0107** [comment]
Thanks Anton! I will try to run on google colab.

**Comment by ravichopra0107** [comment]
Hello AntonMu, I tried to run the model using AWS p2.xlarge instance but ended with the another error. The volume size for the instance was 95 GiB.
![Screenshot from 2021-01-10 14-35-42](https://user-images.githubusercontent.com/56033256/104118744-2c8fa580-5351-11eb-80de-00c4e6adcbf0.png)

**Comment by ravichopra0107** [comment]
I got it worked, the error was with the cuDNN version that comes with aws image. The version is different from what was used to compile the model in our case that is 7.6.5. I tried installing cuDNN 7.6.5 in aws instance and it worked out. Moreover, I put os.environ['CUDA_VISIBLE_DEVICES'] = '-1' in Train_YOLO.py. Thanks, @AntonMu for providing a direction!

**Comment by AntonMu** [comment]
Glad to hear!
