### ISSUE TITLE
Training using GPU has a single core process on the CPU that makes training slow

### ISSUE THREAD

**Issue by MuriloVenturin** [AntonMu/TrainYourOwnYOLO#226]
### Readme 

- I have followed all Readme instructions carefully: Yes

### Troubleshooting Section

- I have looked at the  [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section: Yes

### Troubleshooting Section

- I have looked for [similar issues](https://github.com/AntonMu/TrainYourOwnYOLO/issues?q=is%3Aissue): Yes

### System information
- What is the top-level directory of the model you are using: yolo
- Have I written custom code (as opposed to using a stock example script provided in the repo): I used the script exactly as it is in the repository, just replacing the data as written in the Readme.
- OS Platform and Distribution: Linux Ubuntu 18.04
- TensorFlow version: 2.4.1
- CUDA/cuDNN version: CUDA 11.0/cuDNN 8.0.5
- GPU model and memory: tesla v100-sxm2-16gb
- Exact command to reproduce: Just run the Train_YOLO.py script

### Describe the problem
I am training the model on a remote server with a powerful GPU and a large dataset, after the batch is processed by the GPU there is a single core process that uses the CPU, even with 8 cores available this process uses only 1 core. The processing on the GPU is very fast, but this step on the CPU is making the training slow, when this process is running on the CPU the GPU is idle. This process occurs as soon as the processing of a bach ends and before starting the next batch.

I uploaded some images from the GPU and CPU monitor just for example.

I imagine that the problem is related to the saving of the model (checkpoint) or to the loading of the data of the next batch.

Does anyone know where the problem is and how to fix it?

![Screenshot from 2021-04-29 08-00-46](https://user-images.githubusercontent.com/37968228/116540871-1e927000-a8c1-11eb-88a6-67110c19b851.png)
![Screenshot from 2021-04-29 08-00-57](https://user-images.githubusercontent.com/37968228/116540875-1fc39d00-a8c1-11eb-82d0-2c2dc54f895f.png)

**Comment by MastalerzKamil** [comment]
What about using property allow_growth memory? In default Tensorflow allocate almost all available memory. If you check it as True, it would be better 
https://kobkrit.com/using-allow-growth-memory-option-in-tensorflow-and-keras-dc8c8081bc96

**Comment by bertelschmitt** [comment]
**@MuriloVenturin: This is a Python app, and Python inherently will create only one process using only one core.
Unless the whole thing is rewritten for multiprocessing, adding more cores won't help. 

I have converted TrainYourOwnYOLO for parallel **inference** in multiple streams (albeit not for parallel inference of a single stream). [See here](https://github.com/bertelschmitt/multistreamYOLO)  my [comment below](https://github.com/AntonMu/TrainYourOwnYOLO/issues/199),

I am not smart enough to rewrite the training part for parallel execution, but I would be very interested in seeing it.
Bottom line: If the training part bottle-necks in Python code where one core goes to 100% utilization, the immediate solution would be a box with a faster CPU with higher single-core speed. 
You also want to break out Top and check whether main (not GPU) memory is exhausted during training, causing the box to swap. That would definitely redline CPU utilization. In that case, add more (main) memory.

@MastalerzKamil: As you correctly state, allow_growth (along with gpu_memory_fraction) influences the amount of GPU memory a Tensorflow/Keras process grabs for itself. At default, 100% of available GPU memory is claimed, so  allow_growth/ gpu_memory_fraction would only help in reducing claimed GPU memory. In @MuriloVenturin's case, reducing the GPU memory footprint would have no effect other than making the Tensorflow part run slower. His problem seems to be a bottle-necking Python code, and the wrong assumption that multiple cores should be leveraged.**

**Comment by MuriloVenturin** [comment]
Got it @bertelschmitt, there really doesn't seem to be an easy solution, and paralleling with python doesn't always bring benefits. Thank you for your attention in answering my comment.
