### ISSUE TITLE
Use with OPENCV Python

### ISSUE THREAD

**Issue by TheMaster6417** [AntonMu/TrainYourOwnYOLO#233]
The script used for detecting, doesn't use opencv, is it possible? The trained file is a .h5 and not a weights

Answer found by me:

Convert the Keras Trained file into a .weights and create a config

**Comment by AntonMu** [comment]
Hi @TheMaster6417 - glad you found a solution. I think this has come up before. If you like, please make a PR on your solution to the Readme to become a contributor. Or comment here! Thanks!

**Comment by AntonMu** [comment]
Closing due to staleness.
