### ISSUE TITLE
I have a problem with training yolo with my own dataset

### ISSUE THREAD

**Issue by SayedWakeb** [AntonMu/TrainYourOwnYOLO#234]
i convert coco annotation manually to text file and called the file (data_train.txt) as in repo
`Data/Source_Images/Training_Images/vott-csv-export/0.jpg 255,370,280,415,4 921,408,954,512,4`

and copy my images and data_traun.txt file to folder 
`Data\Source_Images\Training_Images\vott-csv-export`

and put my classes in the file `data_classes.txt`

Then follow the steps as in repo when reach at train 
`python Train_YOLO.py`

got this error 

```
Traceback (most recent call last):
  File "f:/wakeb_projects/astira/2_Training/Train_YOLO.py", line 226, in <module>
    lines = ChangeToOtherMachine(lines, remote_machine="")
  File "f:\wakeb_projects\astira\Utils\Train_Utils.py", line 238, in ChangeToOtherMachine
    suffix = (file.split(repo))[1]
IndexError: list index out of range
```

**Comment by chrysaat** [comment]
Hello! I got the same error. Did you manage to fix it?
