### ISSUE TITLE
Tensorboard no dashboards are active

### ISSUE THREAD

**Issue by cheythomas** [AntonMu/TrainYourOwnYOLO#239]
Does Train_Yolo.py have tensorboard setup?

I saw in one of your answers to run

> tensorboard --logdir Data/Model_Weights

However that does not work either. Still no dashboards are active.

Neither does this also work.

> tensorboard --logdir=training/

**Comment by AntonMu** [comment]
Your first command looks right. 

You can also use weights and biases which offers even more stats.
