### ISSUE TITLE
Which file to use to continue training from previous step?

### ISSUE THREAD

**Issue by MuzziMuzzi** [AntonMu/TrainYourOwnYOLO#240]
If I want to continue training from where I left off, should I use checkpoint.h5 or trained_weights_stage_1.h5 or trained_weights_final.h5?

Changing this
> if FLAGS.is_tiny:
>         model = create_tiny_model(
>             input_shape, anchors, num_classes, freeze_body=2, weights_path=weights_path
>         )
>     else:
>         model = create_model(
>             input_shape, anchors, num_classes, freeze_body=2, weights_path=weights_path
>         )  # make sure you know what you freeze

To this:

> if FLAGS.is_tiny:
>         model = create_tiny_model(
>             input_shape, anchors, num_classes, freeze_body=2, weights_path=checkpoint.h5
>         )
>     else:
>         model = create_model(
>             input_shape, anchors, num_classes, freeze_body=2, weights_path=checkpoint.h5
>         )  # make sure you know what you freeze

**Comment by AntonMu** [comment]
First off, why are you trying to change the code? You can pass the weights file with the command line argument `--weights_path`.

For the checkpoint, you can use whichever you prefer. If you already have a `trained_weights_final.h5` it means the model has been completely trained already and resuming from this wouldn't make sense. `trained_weights_stage_1.h5` is the result after the first stage that just trains the topmost layers. And other checkpoints are saved [periodically during training](https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/Train_YOLO.py#L213). 

Hope this helps!
