### ISSUE TITLE
Unable to run Download_and_Convert_YOLO_weights

### ISSUE THREAD

**Issue by swaticolab** [AntonMu/TrainYourOwnYOLO#242]
Hi,

The code looks great. 
a problem that I have facing while executing **"Download_and_Convert_YOLO_weights.py"**

> `Downloading Raw yolov3.weights
> 
> Traceback (most recent call last):
>   File "C:\Users\swati.o.jain\Desktop\TrainYourOwnYOLO\Data\Model_Weights\Download_Weights.py", line 58, in <module>
>     download_file_from_google_drive(file_id, destination)
>   File "C:\Users\swati.o.jain\Desktop\TrainYourOwnYOLO\Data\Model_Weights\Download_Weights.py", line 45, in download_file_from_google_drive
>     save_response_content(response, destination)
>   File "C:\Users\swati.o.jain\Desktop\TrainYourOwnYOLO\Data\Model_Weights\Download_Weights.py", line 26, in save_response_content
>     bar = progressbar.ProgressBar(max_value=progressbar.UnknownLength)
> TypeError: __init__() got an unexpected keyword argument 'max_value'
> Downloaded Raw yolov3.weights in 6.8 seconds
> 
> 2022-01-07 01:04:11.382538: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
> 2022-01-07 01:04:11.396691: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set 
> up on your machine.
> Loading weights.
> Traceback (most recent call last):
>   File "convert.py", line 286, in <module>
>     _main(parser.parse_args())
>   File "convert.py", line 87, in _main
>     shape=(3,), dtype="int32", buffer=weights_file.read(12)
> TypeError: buffer is too small for requested array`

Although when I download the weights file from the below link (also mentione din your script), the script runs fine:
https://pjreddie.com/media/files/yolov3.weights

Can you guide me on what can be the possible issue here.

I am using a CPU based Windows system.

What is the top-level directory of the model you are using: TrainYourOwnYolo
Have I written custom code (as opposed to using a stock example script provided in the repo): NA. Still trying to understand the error.
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
TensorFlow version (use command below): 2.6.2
CUDA/cuDNN version: CUDA = 10.2.89, cuDNN not installed
GPU model and memory: Using CPCU machine
Exact command to reproduce: python Download_and_Convert_YOLO_weights.py

**Comment by AntonMu** [comment]
I recommend to follow the instructions step by step and complete the issue template if you are still having trouble.
