### ISSUE TITLE
Confidence score and class label not needed to print

### ISSUE THREAD

**Issue by rzeeshan565** [AntonMu/TrainYourOwnYOLO#243]
Hi there,
I have successfully trained and implemented the model but for clear visualization Confidence score and class label not needed to print. can someone help where can I find the line to comment out in the code?

**Comment by AntonMu** [comment]
https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/src/keras_yolo3/yolo.py

**Comment by rzeeshan565** [comment]
thankyou @AntonMu .
