### ISSUE TITLE
Numpy version error and weights not downlaoding

### ISSUE THREAD

**Issue by boqli** [AntonMu/TrainYourOwnYOLO#246]
This repository used to work for me and my custom dataset up until recently. From around 4 days ago i was unable to run it, not even when cloning the github repo. I have even used other computers to run the colab but still the same errors occur. 

System information:
Using Google Colab, cloning this repo.
No changes made to the code, trying to replicate the results claimed by author.
OS: Windows 10 Pro
Requirements file:
tensorflow==2.3.1
Keras==2.4.3
pillow
matplotlib
pandas
opencv-python
progressbar2
wandb
black
GPU model and memory: Google Colab Tesla GPU

Command the provides the error:
%cd /content/TrainYourOwnYOLO/1_Image_Annotation
!python Convert_to_YOLO_format.py

%cd /content/TrainYourOwnYOLO/2_Training
!python Download_and_Convert_YOLO_weights.py

Now, all of a sudden, i keep getting this error 
"RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd"
 and my weights are not being downloaded, the download stops less than a second after it starts.

Downloading Raw yolov3.weights

| |#                                                   | 0 Elapsed Time: 0:00:00
Downloaded Raw yolov3.weights in 0.8 seconds

This model was working well just 4 days ago but not i cannot do anything with these current issues.

I tried using this repo exactly how it is, without my dataset, i also tried updating numpy to the latest version which didn't help either.

**Comment by boqli** [comment]
I hope the information provided above is enough, I am literally opening the jupyter notebook in google colab and executing the cells as they should be executed.

**Comment by AndrewW-GIT** [comment]
I think i may know the cause.
I was testing some changes to make the code run with the latest versions of Python and packages and kept getting

```
    conv_weights = np.ndarray(
TypeError: buffer is too small for requested array
```


effectively meaning the cfg and weights file did not match.
when I downloaded the weights from dark net directly all worked
Recently the weights files downloaded  is just a virus warning from google


```
<!DOCTYPE html><html><head><title>Google Drive - Virus scan warning</title><meta http-equiv="content-type" content="text/html; charset=utf-8"/><style nonce="ypAJ3XlmF67gm0BDWV6R2g">/* Copyright
2022 Google Inc. All Rights Reserved. */
.goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}* html .goog-inline-block,*:first-child+html .goog-inline-block{display:inline}.goog-link-button{position:relati
ve;color:#15c;text-decoration:underline;cursor:pointer}.goog-link-button-disabled{color:#ccc;text-decoration:none;cursor:default}body{color:#222;font:normal 13px/1.4 arial,sans-serif;margin:0}.g
recaptcha-badge{visibility:hidden}.uc-main{padding-top:50px;text-align:center}#uc-dl-icon{display:inline-block;margin-top:16px;padding-right:1em;vertical-align:top}#uc-text{display:inline-block;
max-width:68ex;text-align:left}.uc-error-caption,.uc-warning-caption{color:#222;font-size:16px}#uc-download-link{text-decoration:none}.uc-name-size a{color:#15c;text-decoration:none}.uc-name-siz
e a:visited{color:#61c;text-decoration:none}.uc-name-size a:active{color:#d14836;text-decoration:none}.uc-footer{color:#777;font-size:11px;padding-bottom:5ex;padding-top:5ex;text-align:center}.u
c-footer a{color:#15c}.uc-footer a:visited{color:#61c}.uc-footer a:active{color:#d14836}.uc-footer-divider{color:#ccc;width:100%}</style><link rel="icon" href="null"/></head><body><div class="uc
-main"><div id="uc-dl-icon" class="image-container"><div class="drive-sprite-aux-download-file"></div></div><div id="uc-text"><p class="uc-warning-caption">Google Drive can't scan this file for
viruses.</p><p class="uc-warning-subcaption"><span class="uc-name-size"><a href="/open?id=1ENKguLZbkgvM8unU3Hq1BoFzoLeGWvE_">yolov3.weights</a> (237M)</span> is too large for Google to scan for
viruses. Would you still like to download this file?</p><form id="downloadForm" action="https://docs.google.com/uc?export=download&amp;id=1ENKguLZbkgvM8unU3Hq1BoFzoLeGWvE_&amp;confirm=t" method=
"post"><input type="submit" id="uc-download-link" class="goog-inline-block jfk-button jfk-button-action" value="Download anyway"/></form></div></div><div class="uc-footer"><hr class="uc-footer-d
ivider"></div></body></html>
```

**Comment by joaoalves10** [comment]
@AndrewW-GIT can you give me the link for the pre-weights download?
The download is just a .h5 file or has more files?
