### ISSUE TITLE
Printing model summary

### ISSUE THREAD

**Issue by kbjohnson96** [AntonMu/TrainYourOwnYOLO#248]
This is an excellent repot.  I would like to print the model summary for a trained network.  When performing inference, the model is inside the YOLO object which I can't use to print out details.  When I load in the yolo.h5 file directly it does not seem to be specific to the trained layer dimensions.  

Any help printing out the correct model summary (reflective of filter sizes adapted to input dimensions) would be appreciated.

**Comment by AntonMu** [comment]
The training does not change the model. So the model summary of the final trained model and the pre-trained model will be the same.
