### ISSUE TITLE
IoU threshold for non Max suppression

### ISSUE THREAD

**Issue by Morell1123** [AntonMu/TrainYourOwnYOLO#256]
Hi Anton

I was wondering if there is a place in your code (the detector) where one can set the IoU threshold for non-max-suppression? 
I can't seem to find it.
If the threshold cannot be changed, what is the default?

Kind Regards
Oliver Morell

**Comment by AntonMu** [comment]
It's here https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/src/keras_yolo3/yolo.py#L31 - just search for iou and you find it.
