### ISSUE TITLE
Error when training tiny YOLO on early stopping

### ISSUE THREAD

**Issue by Jaen0302** [AntonMu/TrainYourOwnYOLO#258]
Hi Anton,

  To begin with, I would like to show my appreciation for creating such a great project with details. It helped me a lot with my project. It went all well when I used YOLO, I've finished a project already using it. To speed things up, I tried to train with tinyYOLO, however it fails every time at the 80th or so epoch. The error message I have is:
**Error #1:** Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
         [[{{node PyFunc}}]]
It ends the training earlier than it should have. I've googled this error, and it says that it usually has to do with shapes and layers, and I don't have a clue on how to fix it. 

  It seems to be still fine working on detection for some images, but for some specific images this error just pops out.
**Error #2:** File "D:\Grade3_2nd\總結式課程\tinyYOLOtest\content\TrainYourOwnYOLO\2_Training\src\keras_yolo3\yolo.py", line 225, in detect_image
    out_prediction.append([left, top, right, bottom, c, score])
UnboundLocalError: local variable 'left' referenced before assignment
I've checked how you wrote the python code, and I'm quite sure that these variables were already referenced after assignment.

I've followed all the steps in the README, and the environment is supposed to be correct since I can finish a project with YOLO, but somehow fail on tinyYOLO. I am using Python 3.7.9, Tensorflow 2.4.3, Keras 2.4.3, training with 1243 examples of 9 differrent classes.

There were also some errors that I got that were already from YOLO, but it seems to work out fine so I just waived it. Not sure if this would affect the error mentioned, but here it is.
**Error #3:** layout failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)
**Error #4:** 2022-08-13 20:37:50.063959: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
The subshape error I've seen you mentioned it in other poles, running on CPU would solve the problem for them, but for me it still didn't work. Errors #3&#4 were missing if I ran the project on Google Colab, but for #1&#2 mentioned in the beginning it fails for both CPU and Colab.

Thanks in advance!

Sincerely,
Jaen

**Comment by AntonMu** [comment]
Hi Jaen,

I haven't done too much testing for tiny Yolo. 

Do you have a fork you can share or a colab? Along with some minimal example to reproduce the error?

**Comment by Jaen0302** [comment]
Hi Anton,

  Thank you for such a quick reply! I do have a colab, with the fork in it. Here's the link: https://colab.research.google.com/drive/18r0372CW-Ojo9aON9OyvFQh1joYFDcwu?usp=sharing

As for some minimal example to produce the error, I'm sorry that I do not have it since it only appears after 80 or so epochs. The number is different every time I try it, and do not have a clue about the solution. I do have a picture for the error though, as shown below. For errors #3&#4, it comes out whenever I load tensorflow.


![image](https://user-images.githubusercontent.com/67680733/184497778-f05dc70b-820d-416c-8168-b557ba77c40f.png)

![image](https://user-images.githubusercontent.com/67680733/184497794-b55d015a-3923-4da3-bb15-51c9d1852ac7.png)


Thanks for your help!

Sincerely,
Jaen

**Comment by AntonMu** [comment]
Re the training "error" I think you can ignore that. Early stopping just means that the loss has not improved in x number of epochs and thus it is done training.

If you can run inference on it, it means that it is trained successfully. How are the predictions for those pictures that work? Do they seem ok?

I would try to debug the images you are having trouble with. Are they always the same images or do they change?

**Comment by Jaen0302** [comment]
Hi Anton,

Got it! Thanks a lot~ I'll ignore that error.
Yes, they are always the same images that have problems. I guess it has to do with images that have no detection since it error always comes like this no matter how many times I run it:
![image](https://user-images.githubusercontent.com/67680733/184525706-777a23ee-ca27-49a6-85e5-454780f4bcc4.png)

Really appreciate your help!

Sincerely,
Jaen

**Comment by Jaen0302** [comment]
Hi Anton,

I fixed the error somehow, guessed it was just probably because I moved something in the yolo.py. I re-downloaded and ran it again and it somehow worked...

Thank you for your time and help!

Sincerely,
Jaen
