### ISSUE TITLE
Subproccess call in Download_and_Convert_YOLO_weights.py does not work when using python3

### ISSUE THREAD

**Issue by cole8888** [AntonMu/TrainYourOwnYOLO#26]
The hard-coded variable `call_string` on line 43 of `Download_and_Convert_YOLO_weights.py` is set to `'python convert.py yolov3.cfg yolov3.weights yolo.h5'` which throws a series of module not found errors if you have python 2 and 3 on your system and the modules needed are installed in the python 3 environment.

I solved this by changing the call string to `'python3 convert.py yolov3.cfg yolov3.weights yolo.h5'`. Perhaps this should be mentioned in the readme file?

**Comment by AntonMu** [comment]
Thanks for the hint. If you let me know what you did I will try to reproduce the error. 

If you test it on your machine please make sure you run all commands from within your virtual environment. Otherwise you can encounter errors like the one you mentioned that is related to other python installations.

**Comment by cole8888** [comment]
Sorry, I didn't use a virtual environment as you specified in the documentation, my fault. I did manage to get it working wonderfully without it though after changing that file. 

If you would like to reproduce the error, don't use a virtual environment and install both python 3 and python 2. Install the dependencies using pip3 and run the scripts with python3 and make sure that the `python` command corresponds to the python 2 package. When it executes the `python` call it uses python 2 so it cannot find the required modules since they belong to python 3.

Thanks a bunch, I'll close this since this isn't an issue if you follow the docs, hopefully this helps someone else.

**Comment by AntonMu** [comment]
Hi Cole! Glad to hear it worked! And thanks for providing more details about the issue. I am sure it will help others.
