### ISSUE TITLE
.weight file

### ISSUE THREAD

**Issue by philippederouville** [AntonMu/TrainYourOwnYOLO#36]
Hey, 
I've got my .h5 file which works perfectly!
But one question ... Is it possible to convert .h5 to .weight file ? 
Thanks you ;)

**Comment by AntonMu** [comment]
Hey Phillipe - I am glad it worked for you!

I don't have a direct answer for your question but if your goal is to use your trained model with darknet, then you can try [converting it to *.pb](https://stackoverflow.com/questions/48347829/how-to-convert-pb-files-protobuf-files-to-weight-files-to-use) first. 

Converting *.h5 to *.pb is easier - you can find several implementations such as this [one here](https://stackoverflow.com/questions/45466020/how-to-export-keras-h5-to-tensorflow-pb).

Let me know if that helps and if you find a better solution please post it here!

Thanks!

**Comment by philippederouville** [comment]
Hey! Thank you for your answer. I didn't find an easy way to do it. If someone else has any idea ... ;)
