### ISSUE TITLE
Trying to run the Train_Yolo throws error 

### ISSUE THREAD

**Issue by ShashiAdhikari** [AntonMu/TrainYourOwnYOLO#40]
np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/Shreeni/Downloads/ripo/TrainYourOwnYOLO-master/2_Training/Train_YOLO.py", line 32, in <module>
    from keras_yolo3.yolo3.model import preprocess_true_boxes, yolo_body, tiny_yolo_body, yolo_loss
ModuleNotFoundError: No module named 'keras_yolo3'

**Comment by AntonMu** [comment]
Hi Sashi,

Would you be able to provide more details on the error you are experiencing? Steps that lead to it?

As a first troubleshooting measure, please make sure that you are using a virtual environment as described in the Readme.

Hope this helps!

Anton

**Comment by ShashiAdhikari** [comment]
I am using pycharm to run this

**Comment by AntonMu** [comment]
If you are in Windows please type the following two commands in your IDE:

`set-alias which where.exe`
`which python`

What is the output?

**Comment by ShashiAdhikari** [comment]
you mean the python version i am using

**Comment by AntonMu** [comment]
Can you post the output when you run this command? Thanks.

**Comment by ShashiAdhikari** [comment]
set-alias which where.exe
which python 

this command seems to invalid syntax

**Comment by AntonMu** [comment]
Which OS are you using?

**Comment by ShashiAdhikari** [comment]
windows

**Comment by AntonMu** [comment]
OK, please follow the instructions here https://github.com/AntonMu/TrainYourOwnYOLO#setting-up-virtual-environment-windows so that your virtual environment works.

**Comment by ShashiAdhikari** [comment]
I will try this now and see if it works

**Comment by ShashiAdhikari** [comment]
![image](https://user-images.githubusercontent.com/9759102/68915297-60604280-072f-11ea-98fc-95834ee96b29.png)

**Comment by ShashiAdhikari** [comment]
this is the error i got when I used to run on the virtual environment i have added import tensorflow as tf in the file tough

**Comment by AntonMu** [comment]
Please make sure you install the requirements via pip as described in the
Readme.

**Comment by AntonMu** [comment]
I recommend you to follow the exact steps in the Readme. First try running
the minimal example. Second, try running all steps with the provided data.
Once all this passes and you are comfortable with the code, you can add
your own modifications. But at first, don't add any code in the existing
code.

**Comment by ShashiAdhikari** [comment]
![image](https://user-images.githubusercontent.com/9759102/68997305-d91be780-0872-11ea-8643-ee199317123c.png)
  i didn't added any code

**Comment by ShashiAdhikari** [comment]
yolo.h5 no directory found

**Comment by AntonMu** [comment]
I encourage you to follow the steps in the Readme

https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/README.md#train-yolov3-detector

It looks like you didn't download the pre-trained weights.

**Comment by ShashiAdhikari** [comment]
Thank you

**Comment by AntonMu** [comment]
You are welcome. Good luck with your project!

**Comment by bushra-hafeez** [comment]
Sir, the download-and-convert-pre-trained-weights did run in python 3.7 with some warnings and no error but failed to create Yolo.h5 file ... What could be the reason?

**Comment by AntonMu** [comment]
If you are having problems with the code please use the issue template and
describe your issue. Thank you.
