### ISSUE TITLE
Training Fails

### ISSUE THREAD

**Issue by NiklasWilson** [AntonMu/TrainYourOwnYOLO#41]
I tried to train with the images and annotations provided without changing anything.

Python: v3.7
Tensorflow: v2
System: PI4 2GB RAM (Linux raspberrypi 4.19.75-v7l+ [Buster])

And it fails when running Train_TOLO.py
It fails after starting Epoch 1.

>   File "/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[32,416,416,32] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[node conv2d_1/convolution (defined at /home/pi/.virtualenvs/cv/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_keras_scratch_graph_20380]
Function call stack:
keras_scratch_graph

I can provide more info if needed. Thanks in advance for any insight.
I saw else where that it might be due to memory. I will try to figure that out and update if that does happen to be the case.

**Comment by AntonMu** [comment]
Hi Niklas,

I think you are correct - it is probably due to too little memory. Training a Deep Neural Net on a Raspberry Pi may be a bit ambitious. 

Is there a reason why you want to do that? Even if it had enough memory, training would be extremely slow. I recommend to train the model on your local machine (or on AWS) and then only do the inference on the Pi. 

Have you tried running the `Minimal_Example.py` to see if inference works on the Pi?

**Comment by NiklasWilson** [comment]
Thanks for the quick reply. Ive actually gotten the PI4 to do object detection on live video feeds for TF1 with mobilenet and TF2 with YOLOv3. 

But yes I have no need to actually do training on the PI3, Ive switched to attempting to do the training on win10 machine with 64GB RAM and a GTX1080.

However now I am stuck with with this type of error ODDLY not till Epoch2.

> FileNotFoundError: [Errno 2] No such file or directory: 'X:/Machine_Learning/TrainYourOwnYOLO/Data/Source_Images/Training_Images/vott-csv-export/images100.jpg'

**Comment by AntonMu** [comment]
Ok cool - feel free to share your results here!

**Comment by NiklasWilson** [comment]
>     '`get_session` is not available ' RuntimeError: `get_session` is not available when using TensorFlow 2.0.
Do you happen to have a working detector.py for TF2?

I made one to handle youtube videos based on this other repo but the modal it has seems to fairly expertly hard coded.
https://github.com/zzh8829/yolov3-tf2
It provides me this error when trying to use my new weights file.
> ValueError: You are trying to load a weight file containing 147 layers into a model with 7 layers.

**Comment by AntonMu** [comment]
Hi Niklas,

This repo uses tensorflow 1.14. and has not been tested with tf2.0. It
seems like you already tried to just load the weights in the other model
but it doesn't seem to work.

You probably need to do some digging in the code to make it work. Also, my
repo is able to handle videos and streamed data - but it'll also need some
modifications I presume.

**Comment by NiklasWilson** [comment]
Yes Ive run into a few spots where I had to modify some code to use new TF2 functions.
I was hoping to use your repo to train and that other repo to implement than than eventually merge the two.

The setup you have provided for training is great, much more newbie friendly than the other repo.
Thanks again for you input though, really appreciate it.

**Comment by AntonMu** [comment]
You are welcome.

Great - if you make some progress on converting the code to tf2.0 please
make a PR and I'm happy to review it and potentially even merge it into
master (after some testing).

**Comment by NiklasWilson** [comment]
If I am able to make small adjustments to make it work than I will do that.
So far though comparing your keras_yolo3 files to the yolo3_tf2 in the other repo it looks like it might be a big overhaul. It seems "keras" is now built into TF2.

Your code also uses .h5 files which seem to have been replaced by .tf files in newer TF2 project but they may still be compatible.

**Comment by AntonMu** [comment]
Indeed, it looks like the repo you are looking at is directly implemented
in tf2.0.

It is still possible to use a high level API like keras (the latest release
supports tf2.0) with a tf2.0 backend but it may become less common in the
future.

So another possible avenue would be to update keras to the latest version
and make changes accordingly (tf2.0 is syntax breaking though).

**Comment by AntonMu** [comment]
Hi Niklas,

I was thinking about your problem a little more and thought that you may be able to solve it if you save the entire model instead of just the weights. To do so, just add `model.save(os.path.join(log_dir,'trained_model_final.h5'))` in [Train_YOLO.py](https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/Train_YOLO.py) line 194. 

Tf2.0 then let's you load *.h5 natively -> see [here](https://www.tensorflow.org/guide/keras/save_and_serialize#whole-model_saving)

**Comment by NiklasWilson** [comment]
Thanks I will give that I shot. I managed to get training working via that other repo however 100% of my trained modals/checkpoints in that result in no detections even on the training set data.

Even with low loss results.
I assume these are good numbers? train: 78.9618148803711, val: 87.8269271850586
Not really sure what they mean though as they can't be percentages the in the training begins they start in the tens of thousands, so Im not sure how small these need to get.

> avg_loss.result().numpy()

**Comment by AntonMu** [comment]
Hi Niklas - I don't know much about the other repo. The loss numbers seem okay - not great but it should be good enough to recognize objects in training images at least. Keep us posted if you make progress.

**Comment by NiklasWilson** [comment]
Well I spent days trying different things to get it work. I ended up doing a very simply solution... make TF2 run in TF1 compatibility. Someone else can spend extra time to make it true Tf2, but now it will support TF1 and TF2 the way it is. Assuming you accept the pull request.

**Comment by NiklasWilson** [comment]
@AntonMu On an extra note, how would you feed the training script images with no annotations? Ive read in various places that training on images that do not containing the object can be a large benefit to removing false positives.

For instance with the cat face example, give it images where cats might be, but are none can help.

**Comment by AntonMu** [comment]
Hi Niklas - thanks so much for your work!
