### ISSUE TITLE
TF2.0

### ISSUE THREAD

**Issue by muhammad-maaz-confiz** [AntonMu/TrainYourOwnYOLO#44]
Hi,

Any plan to update to TF2.0 in early future?

**Comment by NiklasWilson** [comment]
It supports TF2 I updated it to add support.

**Comment by AntonMu** [comment]
Hi Muhammad,

Niklas recently added TF2 support in compatibility mode [here](https://github.com/AntonMu/TrainYourOwnYOLO/tree/TF2). It still needs some testing but will be in master soon. 

For true TF2 support - it's on the road map but may take a little while....

**Comment by NiklasWilson** [comment]
Ah yes, its good that it has its own branch. I didn't notice that before.
