### ISSUE TITLE
TF2.0 load_weights() error

### ISSUE THREAD

**Issue by mmaaz60** [AntonMu/TrainYourOwnYOLO#46]
Hi,

While using TF2.0 with TF2 branch on this repo I am getting the "TypeError: load_weights() got an unexpected keyword argument 'skip_mismatch'" error. And if I remove the 'skip_mismatch()' parameter, I get the shape miss match error. Any thoughts?

![load_weights_2](https://user-images.githubusercontent.com/55104795/69795606-538f2480-11ee-11ea-8c71-92a31f079f30.png)
![load_weights](https://user-images.githubusercontent.com/55104795/69795607-538f2480-11ee-11ea-9951-e48086d748db.png)

**Comment by AntonMu** [comment]
Hi!

TF2 is still under development and I won't be able to help you much before
testing it myself.

But - from the message - it seems like you need to update Keras to the
latest version.

Let me know if that works.

**Comment by mmaaz60** [comment]
Thanks @AntonMu,

I was trying to use tf.keras API from TF2.0 which does not support skip_mismatch argument. In the branch TF2.0 in this repo, the keras is being used, which will be deprecated in future. So I would suggest you to manage to use tf.keras API on the final merge for TF2.0 support.

Thanks

**Comment by AntonMu** [comment]
If you found a working fix - please feel free to make a PR and help others
with similar issues. 🙏🏼

**Comment by NiklasWilson** [comment]
@mmaaz60 It seems you have modified my TF2 keras adjustments. What you are trying to do requires many more changes that @AntonMu  (at least atm) does have knowledge of and I personally dont have a desire to learn it when this is working perfectly for my needs at least atm. I made the TF2 keras API work in a TF1 state, so all old features like "skip_mistmatch" still work but any new features wont. There is a lot of code that would need to change to make true use of the TF2 keras API.

**Comment by AntonMu** [comment]
Closing this issue for now. I don't think there is a TF2 implementation, yet.
