### ISSUE TITLE
tensorflow resource exhausted error while running training

### ISSUE THREAD

**Issue by whatohyou** [AntonMu/TrainYourOwnYOLO#53]
I tried to lower the batch size from Train_YOLO.py file to 32->16 and 4->1. Still no luck.
What can I do to make it work?

**Comment by AntonMu** [comment]
What are your GPU specs? Make sure you have enough RAM available.

**Comment by AntonMu** [comment]
I am closing this issue now. If you still encounter problems please file a new issue using the issue template. Thank you!
