### ISSUE TITLE
Not able to detect training images 

### ISSUE THREAD

**Issue by Tharunzeus** [AntonMu/TrainYourOwnYOLO#54]
I'm running the Train_YOLO.py on my CPU and followed the steps. But I'm getting an error: 

[Errno 2] No such file or directory: 'D:/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(42).jpg'

The image is present in my directory but it is not getting detected. Any reason why?

**Comment by AntonMu** [comment]
Hi! Try removing the spaces in your filenames.
