### ISSUE TITLE
Convert output network to tensorflow

### ISSUE THREAD

**Issue by TomasTrnkaPLC** [AntonMu/TrainYourOwnYOLO#58]
Hi.
I have a question. The output is in format .h5 . What is a Keras format. How I can convert him to tensorflow format like pb? I find a few tutorial but he want also *.json file but, i dont have him. Do I need a train network with paramater who eneble -json? What I need for that? Thanks for answer.

**Comment by AntonMu** [comment]
Hi Tomas - please have a look at the previous issue on that topic and post remaining questions there. 

https://github.com/AntonMu/TrainYourOwnYOLO/issues/36#issuecomment-551216008
