### ISSUE TITLE
Error: No such file or directory "example.jpg"

### ISSUE THREAD

**Issue by xK4zut0** [AntonMu/TrainYourOwnYOLO#60]
So after I start training it loads everything appropriatly, but when the first epoch starts I get the error message **"Error: No such file or directory "example.jpg""**. Here is the error traceback. 
[yolotrain problem.txt](https://github.com/AntonMu/TrainYourOwnYOLO/files/4021736/yolotrain.problem.txt)

So basically I'm no entirely sure if that is just the modules way to print the path for error output, but if it isn't I am not sure why the path is escaped by forward slashes **"C:/Users/cooki/Desktop/desktop/..."** instead of backslashes **"path\to\jpg"** since I am running on Windows and your train script is taking the os.path.

**Comment by AntonMu** [comment]
Hi! It has been tested on Windows and it should find the paths. My
recommendation is to have a look at the Readme and follow the instructions
exactly. Once this runs feel free to make modifications as needed. Hope
this helps.

**Comment by AntonMu** [comment]
The first thing I see is that you changed the folder structure and this can
cause problems. Make sure to use `.../TrainYourOwnYolo/Data/...` etc.

**Comment by AntonMu** [comment]
I am closing this issue now. If you still encounter problems please file a new issue using the issue template. Thank you!
