### ISSUE TITLE
how to calculate mAP

### ISSUE THREAD

**Issue by lrscse** [AntonMu/TrainYourOwnYOLO#63]
@AntonMu  hi.. able to successfully  trained and pedicton on some test image.i custom my data for tumor detection in brain mri. i want to know to to able to generate mAP.. will be very thankfull for your help

**Comment by AntonMu** [comment]
Hi @lrscse - you can for instance use this repo to calculate mAP: https://github.com/Cartucho/mAP 

To adapt it, you need to make sure that the order of the corners of the boxes coincides for the different outputs.

**Comment by lrscse** [comment]
@AntonMu  thanks a lot.. and yes i will help others clear their doubt if i am able..  onemore is there any way to generate graph for loss during training.

**Comment by AntonMu** [comment]
Ok, let me know if you encounter any problems getting the mAP to work. With regard to showing the training progress, you can use tensorboard! During training, log files are automatically saved under [Data/Model_Weights](https://github.com/AntonMu/TrainYourOwnYOLO/tree/master/Data/Model_Weights) and the folder name is the current timestamp. 

Thus, if you want to track it, open this folder in tensorboard via:

```
tensorboard --logdir .\Data\Model_Weights\<current timestmap>
```
Then open your browser and type 
```
localhost:6006
```
and you will see your progress.

**Comment by lrscse** [comment]
@AntonMu Thanks for your valuable instructions and taking time to reply my queries.. I guess i have to use same image for train and test in order to calculate mAP otherwise file .txt file will be mismatch.

**Comment by AntonMu** [comment]
Yes - that is correct. You have to use the same images to calculate mAP -
you are comparing the predicted labels against the "true" labels. Ideally
you would want to label a separate test image set which you didn't use for
training. Otherwise your estimate will be optimistic.

**Comment by kevinyx2** [comment]
Hello, are you still on this? lrscse, the conversion from csv to detection-results?

**Comment by Voldy1998** [comment]
Do you have any code to convert the entries in .csv format to .txt format as mentioned in https://github.com/Cartucho/mAP?

**Comment by 648783116** [comment]
Could anyone upload your code for converting our csv to the required file format for mAp calculation? Much appreciated. Feel free to also email me at serene0900@gmail.com

**Comment by 648783116** [comment]
Just confirming xmin, ymin are the left and top, xmax and ymax are the right and bottom for the mAp text file format in https://github.com/Cartucho/mAP?
