### ISSUE TITLE
Question. Using Hyperdash or Weights & Biases 

### ISSUE THREAD

**Issue by seba5496** [AntonMu/TrainYourOwnYOLO#64]
Hey there, i'm wondering how to implement hyperdash or weights & biases apps to the code, specifically i'm having trouble in finding how to record loss and accuracy to these apps while it is running the training. Currently i'm just able to instantiate hyperdash inside the Train_YOLO.py file, but it just records the prompt output 
Any comment would be of great help
Thanks a lot

**Comment by AntonMu** [comment]
Hi! I haven't used either of these frameworks unfortunately. But all log files are saved under Data/Models. See also this reply here https://github.com/AntonMu/TrainYourOwnYOLO/issues/63#issuecomment-573476983

**Comment by seba5496** [comment]
> Hi! I haven't used either of these frameworks unfortunately. But all log files are saved under Data/Models. See also this reply here [#63 (comment)](https://github.com/AntonMu/TrainYourOwnYOLO/issues/63#issuecomment-573476983)

I was able to launch tensorboard but it only records loss, any idea on how to record other metrics like accuracy, precision, recall, etc?

**Comment by AntonMu** [comment]
Have a look at this issue - this should answer most of your questions: https://github.com/AntonMu/TrainYourOwnYOLO/issues/27 There is also an issue on implementing mAP which is relevant: https://github.com/AntonMu/TrainYourOwnYOLO/issues/63

**Comment by AntonMu** [comment]
Hi @seba5496 - support for Weights & Biases has been added.
