### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by bushra-hafeez** [AntonMu/TrainYourOwnYOLO#73]
Hi, I am having the issue in training part.
I had issues in download and convert pre trained weights file , so I tried to run it in spyder and it worked i.e .h5 file is created now. but now there is following error when I run train_YOLO.py although the file 2Q__.jpg exists in vott-csv-export folder

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/me/Desktop/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/2Q__.jpg'

And when I tried to run same train_YyOLO file in python 3.7, it gives following error
AttributeError: module 'keras.backend' has no attribute 'control_flow_ops'

**Comment by abbasmalik514** [comment]
I am facing the same problem? The real reason is, somehow our python script splitting the name of the first folder into two words as TrainYourOwnYOLO and -master. But I can't figure that out how it happens?

**Comment by abbasmalik514** [comment]
The second problem which you are facing is due to the up-gradation of TensorFlow to 2.0. In order to use while_loop in this particular problem, you can use tensorflow.while_loop.

**Comment by abbasmalik514** [comment]
I have figured that out, the path problem which we are facing is coming from the following code as after printing lines, it gives me the wrong path as follows:
/home/abbasmalik/Downloads/Compressed/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images

val_split = FLAGS.val_split
    with open(FLAGS.annotation_file) as f:
        lines = f.readlines()

**Comment by abbasmalik514** [comment]
In Train_YOLO.py I just removed two lines:
lines = ChangeToOtherMachine(lines, remote_machine="")
np.random.shuffle(lines)
and it worked.

**Comment by bushra-hafeez** [comment]
I commented out the lines you mentioned and it worked for me, thank you .
But I didn't get your point about while_loop, there is no while loop in the train_yolo code.

**Comment by abbasmalik514** [comment]
Sorry, I forgot to mention that this is in the model.py file. The path is as follow:
`TrainYourOwnYOLO-master/2_Training/src/keras_yolo3/yolo3/model.py`
