### ISSUE TITLE
Not running on GPU

### ISSUE THREAD

**Issue by Sreedeepthinukala** [AntonMu/TrainYourOwnYOLO#74]
Hello, 

I am not able to run this code on GPU. These are my specs:
1. Windows 10
2. Tensorflow 1.15
3. Nvidia GeForce GTX1070
4. CUDA 9 ( this is the only thing that allowed me to run the code)
5. cudnn-9.0-windows10-x64-v7.6.3.30
6. Python 3.7

`print(tf.test.is_gpu_available())
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
from keras import backend as K
print(K.tensorflow_backend._get_available_gpus())
print(tf.__version__)`

Gives 

`False
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10565893046328515488
]
[]
1.15.0`

Any suggestions?

Thank you

**Comment by AntonMu** [comment]
Check out this link: https://www.tensorflow.org/install/source#tested_build_configurations
