### ISSUE TITLE
Error while running the TrainYOLO.py file

### ISSUE THREAD

**Issue by divy-14** [AntonMu/TrainYourOwnYOLO#75]
When I am running the Train_YOLO.py file it gets an error at line 217 i.e callbacks=[logging, checkpoint], here is the attached image regarding the error.

![Screenshot 2020-01-26 03 53 44](https://user-images.githubusercontent.com/43966117/73128062-d286ba80-3fef-11ea-9c0f-c427368f6d7d.png)

I don't know why is it is showing this error I have tried to feed in the path myself for all the parameters but the problem still persists.

**Comment by AntonMu** [comment]
Hi @divy-14 - thanks for your message. 

Two things:
 * Don't change the folder structure. Just put everything under `C:\TrainYourOwnYOLO\...` to begin with. See [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section for more details.
 * If you would like to have help, I recommend using the [issue template](https://github.com/AntonMu/TrainYourOwnYOLO#filing-an-issue).
