### ISSUE TITLE
AttributeError: 'Model' object has no attribute '_get_distribution_strategy'

### ISSUE THREAD

**Issue by Voldy1998** [AntonMu/TrainYourOwnYOLO#77]
when i am running python Train_YOLO.py
I am getting the following error :
 File "C:\Users\ANJANA~1\Envs\custom\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 1532, in set_model
    self.log_dir, self.model._get_distribution_strategy())  # pylint: disable=protected-access
AttributeError: 'Model' object has no attribute '_get_distribution_strategy'

What has to be done

**Comment by Voldy1998** [comment]
It's been resolved. 
Do you know how much time will it take to train?
In my case it did 51 epocs now its doing 102 epochs and at the 66th epoch and 73rd iteration there is no progress. It's been stuck there

**Comment by lili-miner** [comment]
I am stucked by the same problem, how did you solve it?
![image](https://user-images.githubusercontent.com/53122135/74606000-cc27c200-5107-11ea-9cef-fe68d61868db.png)

**Comment by lrscse** [comment]
hi @Voldy1998  how did u solve the above problem u mention... me facing same problem..

**Comment by allen02** [comment]
I have the same issue @AntonMu  @Voldy1998 

  File "C:\ProgramData\Miniconda3\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 1532, in set_model
    self.log_dir, self.model._get_distribution_strategy())  # pylint: disable=protected-access
AttributeError: 'Model' object has no attribute '_get_distribution_strategy'

**Comment by johnj44** [comment]
the solution is here:
https://www.jianshu.com/p/9da54361d289

good luck!
