### ISSUE TITLE
Anyone could give me a tips for how to get the number of bbox?

### ISSUE THREAD

**Issue by yhc1994** [AntonMu/TrainYourOwnYOLO#81]
Hi,

I would like to know how to print out the number of bbox in the inferenced image?
For example, how many cat_face in a image?
Very thanks for your help in advance

**Comment by AntonMu** [comment]
Hi @yhc1994 - you will have a csv file with the [detection results](https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/Data/Source_Images/Test_Image_Detection_Results/Detection_Results.csv). There, each row corresponds to one detected object. Hope this helps!
