### ISSUE TITLE
E-mail alert & Optimal time of person activity support in the script?

### ISSUE THREAD

**Issue by akshayjaryal603** [AntonMu/TrainYourOwnYOLO#82]
Hi Anton, I am stuck in these issues can you please help me to overcome them. Please refer to any link where I refer to these problems solutions.

1. A script that generates an E-mail alert when any unusual activity has occurred.
2. Find the optimal time of the person doing an activity to filling an empty box.

Please help
Thanks, Anton for this helpful code.

**Comment by AntonMu** [comment]
Hi @akshayjaryal603 
There are several python libraries that allow you to send emails. For instance [here](https://docs.python.org/3/library/email.examples.html). Once something unusual happens you can trigger to send an email. For the second question, I'm not exactly sure what you mean. Can you provide an example or reformulate the question? Thanks!

**Comment by akshayjaryal603** [comment]
Hi, Anton

My second question is let's take an example:

A worker working in a company and he is continuously doing the same task and I set a time limit of 1 minute for filling one box. Now, I want to find out the person doing his task on time or he is wasting time in other activities. If he is doing unnecessary activities then I alert his manager through email alerts.
This is my problem statement. I am a newbie to Deep Learning. Please help.
Thanks for the help, Anton!

**Comment by AntonMu** [comment]
Hi! There are definitely ways of doing such a task but I don't think it's a good idea to use AI to spy on people this way. As long as the worker is doing their job at the end of the day they should be allowed to take a break. So unfortunately, I don't think I'm able to help you with this use case.

**Comment by akshayjaryal603** [comment]
Thanks AntonMu/TrainYourOwnYOLO I appreciate with your help. My question is
not in that sense I just want to learn if this implementation is
possible or not.

I am newbie to Computer Vision. Please let me know if their is great course
which help me to excel in my Computer Vision career.

Thanks Anton for your support!
