### ISSUE TITLE
requirements.txt: tensorflow-estimator

### ISSUE THREAD

**Issue by cepatterson** [AntonMu/TrainYourOwnYOLO#84]
### System information
- **What is the top-level directory of the model you are using**: ‎⁨/⁨Users⁩/cpatterson⁩/TrainYourOwnYOLO/
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.14.6
- **TensorFlow version (use command below)**: v1.15.0-92-g5d80e1e8e6 1.15.2
- **Exact command to reproduce**: pip install -r requirements.txt

### Describe the problem
When I install the requirements, I get the following error: 

ERROR: tensorflow 1.15.2 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 1.15.0 which is incompatible.

### Source code / logs
(env) idc113-01:TrainYourOwnYOLO cpatterson$ pip install -r requirements.txt
Requirement already satisfied: setuptools>=41.0.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (45.1.0)
Requirement already satisfied: pip>=19.0.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (20.0.2)
Requirement already satisfied: absl-py==0.7.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (0.7.1)
Requirement already satisfied: astor==0.8.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (0.8.0)
Requirement already satisfied: attrs==19.1.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (19.1.0)
Requirement already satisfied: backcall==0.1.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (0.1.0)
Requirement already satisfied: bleach==3.1.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 7)) (3.1.0)
Requirement already satisfied: certifi==2019.6.16 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 8)) (2019.6.16)
Requirement already satisfied: chardet==3.0.4 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 9)) (3.0.4)
Requirement already satisfied: cycler==0.10.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 10)) (0.10.0)
Requirement already satisfied: decorator==4.4.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 11)) (4.4.0)
Requirement already satisfied: defusedxml==0.6.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 12)) (0.6.0)
Requirement already satisfied: progressbar2==3.46.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 13)) (3.46.1)
Requirement already satisfied: entrypoints==0.3 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 14)) (0.3)
Requirement already satisfied: gast==0.2.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 15)) (0.2.2)
Requirement already satisfied: google-pasta==0.1.7 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 16)) (0.1.7)
Requirement already satisfied: grpcio==1.22.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 17)) (1.22.0)
Requirement already satisfied: h5py==2.9.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 18)) (2.9.0)
Requirement already satisfied: idna==2.8 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 19)) (2.8)
Requirement already satisfied: ipykernel==5.1.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 20)) (5.1.1)
Requirement already satisfied: ipython==7.6.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 21)) (7.6.1)
Requirement already satisfied: ipython-genutils==0.2.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 22)) (0.2.0)
Requirement already satisfied: ipywidgets==7.5.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 23)) (7.5.0)
Requirement already satisfied: jedi==0.14.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 24)) (0.14.0)
Requirement already satisfied: Jinja2==2.10.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 25)) (2.10.1)
Requirement already satisfied: joblib==0.13.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 26)) (0.13.2)
Requirement already satisfied: jsonschema==3.0.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 27)) (3.0.1)
Requirement already satisfied: jupyter==1.0.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 28)) (1.0.0)
Requirement already satisfied: jupyter-client==5.3.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 29)) (5.3.0)
Requirement already satisfied: jupyter-console==6.0.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 30)) (6.0.0)
Requirement already satisfied: jupyter-core==4.5.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 31)) (4.5.0)
Requirement already satisfied: Keras==2.2.4 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 32)) (2.2.4)
Requirement already satisfied: Keras-Applications==1.0.8 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 33)) (1.0.8)
Requirement already satisfied: Keras-Preprocessing==1.1.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 34)) (1.1.0)
Requirement already satisfied: kiwisolver==1.1.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 35)) (1.1.0)
Requirement already satisfied: Markdown==3.1.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 36)) (3.1.1)
Requirement already satisfied: MarkupSafe==1.1.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 37)) (1.1.1)
Requirement already satisfied: matplotlib==3.0.3 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 38)) (3.0.3)
Requirement already satisfied: mistune==0.8.4 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 39)) (0.8.4)
Requirement already satisfied: mpmath==1.1.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 40)) (1.1.0)
Requirement already satisfied: nbconvert==5.5.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 41)) (5.5.0)
Requirement already satisfied: nbformat==4.4.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 42)) (4.4.0)
Requirement already satisfied: notebook==5.7.8 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 43)) (5.7.8)
Requirement already satisfied: numpy==1.16.4 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 44)) (1.16.4)
Requirement already satisfied: opencv-python==4.1.0.25 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 45)) (4.1.0.25)
Requirement already satisfied: pandas==0.24.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 46)) (0.24.2)
Requirement already satisfied: pandocfilters==1.4.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 47)) (1.4.2)
Requirement already satisfied: parso==0.5.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 48)) (0.5.0)
Requirement already satisfied: pexpect==4.7.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 49)) (4.7.0)
Requirement already satisfied: pickleshare==0.7.5 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 50)) (0.7.5)
Requirement already satisfied: Pillow==6.2.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 51)) (6.2.1)
Requirement already satisfied: prometheus-client==0.7.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 52)) (0.7.1)
Requirement already satisfied: prompt-toolkit==2.0.9 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 53)) (2.0.9)
Requirement already satisfied: protobuf==3.8.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 54)) (3.8.0)
Requirement already satisfied: ptyprocess==0.6.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 55)) (0.6.0)
Requirement already satisfied: Pygments==2.4.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 56)) (2.4.2)
Requirement already satisfied: pyparsing==2.4.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 57)) (2.4.0)
Requirement already satisfied: pyrsistent==0.15.3 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 58)) (0.15.3)
Requirement already satisfied: python-dateutil==2.8.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 59)) (2.8.0)
Requirement already satisfied: pytz==2019.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 60)) (2019.1)
Requirement already satisfied: PyYAML==5.1.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 61)) (5.1.1)
Requirement already satisfied: pyzmq==18.0.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 62)) (18.0.2)
Requirement already satisfied: qtconsole==4.5.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 63)) (4.5.1)
Requirement already satisfied: requests==2.22.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 64)) (2.22.0)
Requirement already satisfied: scikit-learn==0.21.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 65)) (0.21.2)
Requirement already satisfied: scipy==1.3.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 66)) (1.3.0)
Requirement already satisfied: Send2Trash==1.5.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 67)) (1.5.0)
Requirement already satisfied: six==1.12.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 68)) (1.12.0)
Requirement already satisfied: sklearn==0.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 69)) (0.0)
Requirement already satisfied: sympy==1.4 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 70)) (1.4)
Requirement already satisfied: tensorboard==1.15.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 71)) (1.15.0)
Requirement already satisfied: tensorflow==1.15.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 72)) (1.15.2)
Collecting tensorflow-estimator==1.15.0
  Using cached tensorflow_estimator-1.15.0-py2.py3-none-any.whl (503 kB)
Requirement already satisfied: termcolor==1.1.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 74)) (1.1.0)
Requirement already satisfied: terminado==0.8.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 75)) (0.8.2)
Requirement already satisfied: testpath==0.4.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 76)) (0.4.2)
Requirement already satisfied: tornado==6.0.3 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 77)) (6.0.3)
Requirement already satisfied: traitlets==4.3.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 78)) (4.3.2)
Requirement already satisfied: urllib3==1.25.3 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 79)) (1.25.3)
Requirement already satisfied: wcwidth==0.1.7 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 80)) (0.1.7)
Requirement already satisfied: webencodings==0.5.1 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 81)) (0.5.1)
Requirement already satisfied: Werkzeug==0.15.4 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 82)) (0.15.4)
Requirement already satisfied: widgetsnbextension==3.5.0 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 83)) (3.5.0)
Requirement already satisfied: wrapt==1.11.2 in ./env/lib/python3.6/site-packages (from -r requirements.txt (line 84)) (1.11.2)
Requirement already satisfied: python-utils>=2.3.0 in ./env/lib/python3.6/site-packages (from progressbar2==3.46.1->-r requirements.txt (line 13)) (2.3.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./env/lib/python3.6/site-packages (from ipython==7.6.1->-r requirements.txt (line 21)) (0.1.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in ./env/lib/python3.6/site-packages (from tensorboard==1.15.0->-r requirements.txt (line 71)) (0.34.2)
Requirement already satisfied: opt-einsum>=2.3.2 in ./env/lib/python3.6/site-packages (from tensorflow==1.15.2->-r requirements.txt (line 72)) (3.1.0)
ERROR: tensorflow 1.15.2 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 1.15.0 which is incompatible.

**Comment by AntonMu** [comment]
Hi @cepatterson - thank you for raising that issue. There could be a problem with tensorflow versions. Github suggested me to update tf 15 to 15.2. 

To remedy this, installing tensorflow-estimator 1.15.1 should work. It is not a major version change so I expect that all the code will still work. 

Hope this helps!

**Comment by cepatterson** [comment]
Hi @AntonMu -- thanks for getting back with me so quickly!  I tried that and had other issues.  So, I wanted to make sure this wasn't the root cause.  I'll document the subsequent issues and post them as a new issue.  Thanks!
