### ISSUE TITLE
Tensorflow Issue

### ISSUE THREAD

**Issue by Mostafa-Nakhaei** [AntonMu/TrainYourOwnYOLO#86]
I am writing this to help other people who may get the same issues. After spending few hours I resolved them. To begin with, thank you, Anton, for your incredible Repo. 

Problem 1: I had Python 3.8.0 installed on my system. When I was attempting this "pip install tensorflow==1.15.2" it said, "**no module named tensorflow**". 

fix:
To resolve this I had to switch to Python 3.6 version. 

Problem 2: After fixing above, I had a very strange error when running Minimal_Example.py. The error was:     "from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found."

Fix:
Pip uninstall protobuf
pip install protobuf==3.6.0

Hope this is helpful.
Mostafa

**Comment by AntonMu** [comment]
Hi @Mostafa-Nakhaei 

I am glad you enjoy the repo and yhank you so much for pointing this out and sharing it with others. I tried it myself and can confirm that I hit the same issue with `pip install tensorflow==1.15.2`.

I will add a note that this has repo has only been tested with python 3.6.
