### ISSUE TITLE
No module named 'keras_yolo3'

### ISSUE THREAD

**Issue by SergheiDinu** [AntonMu/TrainYourOwnYOLO#87]
Before filing a report consider the following two questions:

### Have you followed the instructions exactly (word by word)?
Yes
### Have you checked the [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section?
Yes
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 8.1 
- **TensorFlow version (use command below)**:
tensorflow==1.15.2
- **CUDA/cuDNN version**:
Cuda 9.0
- **GPU model and memory**:

- **Exact command to reproduce**:

When I try to run: 
from keras_yolo3.yolo import YOLO, detect_video
issue No module named 'keras_yolo3 comes... 
Up to this, I did only this code, maybe somewhere in files is this module explained how to install.>
Here is my code, on Python 3.7 on Spyder.

# -*- coding: utf-8 -*-
"""
Created on Wed Feb 12 21:00:36 2020

@author: Dinu
"""
from PIL import Image
from os import path, makedirs
import os
import re
import pandas as pd
import sys
import argparse

def get_parent_dir(n=1):
    """ returns the n-th parent dicrectory of the current
    working directory """
    current_path = os.path.dirname(os.path.abspath('C:\\Users\\Dinu\\Desktop\\AI postari\\1 proiect'))
    for k in range(n):
        current_path = os.path.dirname(current_path)
    return current_path

sys.path.append(os.path.join('C:\\Users\\Dinu\\Desktop\\AI postari\\1 proiect', "Utils"))
from Convert_Format import convert_vott_csv_to_yolo

Data_Folder = os.path.join('C:\\Users\\Dinu\\Desktop\\AI postari\\1 proiect', "Data")
VoTT_Folder = os.path.join(
    Data_Folder, "Source_Images", "Training_Images", "vott-csv-export"
)
VoTT_csv = os.path.join(VoTT_Folder, "Annotations-export.csv")
YOLO_filename = os.path.join(VoTT_Folder, "data_train.txt")

model_folder = os.path.join(Data_Folder, "Model_Weights")
classes_filename = os.path.join(model_folder, "data_classes.txt")

if __name__ == "__main__":
    # surpress any inhereted default values
    parser = argparse.ArgumentParser(argument_default=argparse.SUPPRESS)
    """
    Command line options
    """
    parser.add_argument(
        "--VoTT_Folder",
        type=str,
        default=VoTT_Folder,
        help="Absolute path to the exported files from the image tagging step with VoTT. Default is "
        + VoTT_Folder,
    )

    parser.add_argument(
        "--VoTT_csv",
        type=str,
        default=VoTT_csv,
        help="Absolute path to the *.csv file exported from VoTT. Default is "
        + VoTT_csv,
    )
    parser.add_argument(
        "--YOLO_filename",
        type=str,
        default=YOLO_filename,
        help="Absolute path to the file where the annotations in YOLO format should be saved. Default is "
        + YOLO_filename,
    )

    FLAGS = parser.parse_args()

    # Prepare the dataset for YOLO
    multi_df = pd.read_csv(FLAGS.VoTT_csv)
    labels = multi_df["label"].unique()
    labeldict = dict(zip(labels, range(len(labels))))
    multi_df.drop_duplicates(subset=None, keep="first", inplace=True)
    train_path = FLAGS.VoTT_Folder
    convert_vott_csv_to_yolo(
        multi_df, labeldict, path=train_path, target_name=FLAGS.YOLO_filename
    )

    # Make classes file
    file = open(classes_filename, "w")

    # Sort Dict by Values
    SortedLabelDict = sorted(labeldict.items(), key=lambda x: x[1])
    for elem in SortedLabelDict:
        file.write(elem[0] + "\n")
    file.close()

"download pre trained dark-net weights and gonna convert them to YOLO format"
import os
import subprocess
import time
import sys
import argparse
import requests
import progressbar

FLAGS = None

root_folder = os.path.dirname(os.path.abspath('C:\\Users\\Dinu\\Desktop\\AI postari\\1 proiect\\2_Training\\src\\'))
download_folder = os.path.join(root_folder, "src", "keras_yolo3")

if __name__ == "__main__":
    # Delete all default flags
    parser = argparse.ArgumentParser(argument_default=argparse.SUPPRESS)
    """
    Command line options
    """
    parser.add_argument(
        "--download_folder",
        type=str,
        default=download_folder,
        help="Folder to download weights to. Default is " + download_folder,
    )

    FLAGS = parser.parse_args()

    url = "https://pjreddie.com/media/files/yolov3.weights"
    r = requests.get(url, stream=True)

    f = open(os.path.join(download_folder, "yolov3.weights"), "wb")
    file_size = int(r.headers.get("content-length"))
    chunk = 100
    num_bars = file_size // chunk
    bar = progressbar.ProgressBar(maxval=num_bars).start()
    i = 0
    for chunk in r.iter_content(chunk):
        f.write(chunk)
        bar.update(i)
        i += 1
    f.close()

    call_string = "python convert.py yolov3.cfg yolov3.weights yolo.h5"

    subprocess.call(call_string, shell=True, cwd=download_folder)

"Detector pasul 3"
import os
import sys

def get_parent_dir(n=1):
    """ returns the n-th parent dicrectory of the current
    working directory """
    current_path = os.path.dirname(os.path.abspath('C:\\Users\\Dinu\\Desktop\\AI postari\\1 proiect'))
    for k in range(n):
        current_path = os.path.dirname(current_path)
    return current_path

src_path = os.path.join(get_parent_dir(1), "2_Training", "src")
utils_path = os.path.join(get_parent_dir(1), "Utils")

sys.path.append(src_path)
sys.path.append(utils_path)

################
Then when i'm trying to do inference... Issue comes.

**Comment by akshayjaryal603** [comment]
First, run this python file - ./2_Training/Download_and_Convert_YOLO_weights.py. After running then try again to run Train or Detector code.

**Comment by RenuPatel1** [comment]
2021-06-02 17:39:27.084684: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-06-02 17:39:27.084875: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "Train_YOLO.py", line 38, in <module>
    from keras_yolo3.yolo3.model import (
ModuleNotFoundError: No module named 'keras_yolo3'


Unable to solve this error, if someone can help in this.

**Comment by akshayjaryal603** [comment]
Follow my suggestion above you can resolve your problem easily.

**Comment by DataReset** [comment]
I have this problem too
It throws an exception, but i ran Download_and_Convert_YOLO_weights.py without exceptions
