### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

### ISSUE THREAD

**Issue by kdk2612** [AntonMu/TrainYourOwnYOLO#88]
Before filing a report consider the following two questions:

### Have you followed the instructions exactly (word by word)?
Yes. Have installed the required libraries from the requirements_cpu.txt
Not able to start training.

### Have you checked the [troubleshooting](https://github.com/AntonMu/TrainYourOwnYOLO#troubleshooting) section?
Yes

------------------------

### System information
- **What is the top-level directory of the model you are using**:

- **Have I written custom code (as opposed to using a stock example script provided in the repo)**:
No, just extracted the code from the files into a Jupyter Notebook.

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
MacBook, macOS Catalina - version 10.15.3

- **TensorFlow version (use command below)**:
v1.14.0-rc1-22-gaf24dc91b5 1.14.0

- **CUDA/cuDNN version**:
Not using CUDA

- **GPU model and memory**:
NA
- **Exact command to reproduce**:

```
print(weights_path)
"/Documents/PythonWorkSpace/ObjectDetection/Yolov3/TrainYourOwnYOLO-TF2/Modified_code/src/keras_yolo3/yolo.h5"

model = create_model(input_shape, anchors, num_classes,
        freeze_body=2, weights_path = weights_path) # make sure you know what you freeze

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-2555863472d6> in <module>
      4 else:
      5     model = create_model(input_shape, anchors, num_classes,
----> 6         freeze_body=2, weights_path = weights_path) # make sure you know what you freeze
      7 
      8 log_dir_time = os.path.join(log_dir,'{}'.format(int(time())))

<ipython-input-14-dad9bb0414b7> in create_model(input_shape, anchors, num_classes, load_pretrained, freeze_body, weights_path)
     28             weights_path='keras_yolo3/model_data/yolo_weights.h5'):
     29     '''create the training model'''
---> 30     K.clear_session() # get a new session
     31     image_input = Input(shape=(None, None, 3))
     32     h, w = input_shape

/opt/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in clear_session()
     86     global _SESSION
     87     global _GRAPH_LEARNING_PHASES
---> 88     tf.reset_default_graph()
     89     reset_uids()
     90     _SESSION = None

AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'
```

### Describe the problem
I keep getting error while creating the model. I have created a new environment to run the code and solve the mentioned issue. Uninstalled the existing libraries and installed the versions mentioned in the repo. 
This error still exists.

**Comment by SergheiDinu** [comment]
I had this problem and I found that we have to install CUDA 9.0. It could help you.

**Comment by kdk2612** [comment]
I am not using GPU.

**Comment by AntonMu** [comment]
Please have a look at the troubleshooting section https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/README.md (point 1). Hope this helps.
