### ISSUE TITLE
KeyError: 'val_loss'

### ISSUE THREAD

**Issue by HajerAa** [AntonMu/TrainYourOwnYOLO#93]
Hi, while running the Train_YOLO.py command i got the following error after achieving Epoch 51/51 

Traceback (most recent call last):
  File "Train_YOLO.py", line 229, in <module>
    step1_val_loss = np.array(history.history["val_loss"])
KeyError: 'val_loss'

I've tried the tutorial one month ago and it was perfectly working. 

-TF version: 2.0
-OS: windows 10
-Using CPU

**Comment by yashj645** [comment]
HajerAa did you find any solution for this i am also stuck on this ?

**Comment by ikomhoog** [comment]
i got this error when only having 9 images to learn from with 0 validation images.
I got more images(41) and got 4 validation images, now i dont get this error anymore
Instead it goes further:
Epoch 51/51
1/1 [==============================] - 61s 61s/step - loss: 195.4055 - val_loss: 165.8527
Unfreeze all layers.
Train on 41 samples, val on 4 samples, with batch size 4.
Epoch 52/102

**Comment by yashj645** [comment]
thank you @ikomhoog i will try with more images
