### ISSUE TITLE
code using

### ISSUE THREAD

**Issue by shima97** [AntonMu/TrainYourOwnYOLO#96]
dear Anton
i have trained the yolo with my own data but i need to use the code for several videos and i don't know how can i give data address in the code. would you please help me on that?

**Comment by AntonMu** [comment]
Hi @shima97 - I am not 100% sure what you mean. If you like to train on videos, make sure to pass in the file format as a command-line argument as well as the folder to your videos as input path. Like this:

```
python Detector.py --file_types .mp4 --input_path <video_folder>
```

**Comment by shima97** [comment]
Thank you for your response,
I think i have asked badly
let me explain: i am going to use your test code trained with my own dataset as a function in a whole code in which a video has been read . in the other word, you give address of the video but i want to run my own whole code on a frame of video and i need your test code as a function to use for this frame.  now would you please explain me these questions:
1. How can i use your test code as a function for this reason
2. Why the file with .h5 format  which has been created in your train code can not be used in other codes?
I am looking for your answer
Yours faithfully
