### ISSUE TITLE
Continue training after temporary stop

### ISSUE THREAD

**Issue by henryangminh** [AntonMu/TrainYourOwnYOLO#97]
I'm training large dataset on Google Colab. It's really useful for me. But I have one problem. Can I save current process training for continue training later?

**Comment by AntonMu** [comment]
Hi @henryangminh - you should be able to do this. You can export the checkpoint to a file and then resume training from there. Currently, that is not implemented in the code but most pieces are there. For instance, in the [train script line 166-172]( https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/2_Training/Train_YOLO.py#L166-L172) the ModelCheckpoint object is defined. You can use this to save and restore the model. Currently, a checkpoint is saved after the initial 51 epochs and then again at the end of 102 epochs.
