### ISSUE TITLE
FileNotFoundError when running train_YOLO.py

### ISSUE THREAD

**Issue by RobinMadelief** [AntonMu/TrainYourOwnYOLO#99]
I have checked the troubleshooting page.

------------------------

### System information
- **What is the top-level directory of the model you are using**: C:\Users\[myname]\Desktop\TrainYourOwnYOLO-master
- **Have I written custom code (as opposed to using a stock example script provided in the repo)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **TensorFlow version (use command below)**: 1.15.2
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**: train_YOLO.py

I am using the cat images that were provided with the code. 

When I run the script train_YOLO.py, I get a FileNotFound error for the images. The error is:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/[myname]/Desktop/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/images%20(62).jpg'

I think it is due to the fast that the code slightly changes the folder. The actual folder is:
C:/Users/[myname]/Desktop/TrainYourOwnYOLO-master/Data/Source_Images/Training_Images/vott-csv-export
However, the script changes .../TrainYourOwnYOLO-master/... to ... /TrainYourOwnYOLO/-master/...

I found my way around it by changing the name of the master folder to 'TrainYourOwnYOLO' (without the -master part), but I wanted to report this issue in case more people run into it.

**Comment by AntonMu** [comment]
Hi! Please carefully check the troubleshooting section (Point 1). Hope this
helps.

**Comment by baldellimtt** [comment]
I'm facing the same error, changing the name of master folder to "TrainYourOwnYolo" does not resolve the issue: 

    image = Image.open(line[0])
  File "C:\Users\Matteo\Anaconda3\lib\site-packages\PIL\Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Matteo/Desktop/TrainYourOwnYOLO/-master/Data/Source_Images/Training_Images/vott-csv-export/9k_%2520(4).jpg'

**Comment by RobinMadelief** [comment]
@baldellimtt it looks like the '-master' is still in your master folder though. Did you try closing and restarting the code after changing the name of the folder?

**Comment by baldellimtt** [comment]
I simply changed the name of the folder to "C:/Users/Matteo/Desktop/TrainYourOwnYOLO/", close the terminal and restart. Is there a way to change the path in the code?

**Comment by baldellimtt** [comment]
fixed, there still was the old path with '-master' in "data_train.txt" file. 
Thank you @RobinMadelief

**Comment by Subhrabiswas** [comment]
@baldellimtt i am facing the same trouble. I have changed the name but like you have mentioned that you had to change it in the data_train.txt file, I am not being able to find the file..could you please help me

**Comment by baldellimtt** [comment]
Hello,
you have to change the paths of the images present in this file:
TrainYourOwnYOLO\Data\Source_Images\Training_Images\vott-csv-export\data_train.txt

you must set it like this:
TrainYourOwnYOLO\Data\Source_Images\Training_Images\vott-csv-export\2Q__%2520(1).jpg
29,17,105,90,0

deleting the "-master" after TrainYourOwnYolo.





Il giorno mar 24 mar 2020 alle ore 15:00 Subhrabiswas <
notifications@github.com> ha scritto:
